# From tutorial here
# https://medium.freecodecamp.org/how-to-continuously-deploy-a-static-website-in-style-using-github-and-aws-3df7ecb58d9c

version: 0.2
phases:
  install:
    commands:
      - echo "install step"
      - npm install
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - echo "build step"
      - npm build
  post_build:
    commands:
      - echo "post_build step"
      - printenv
      - aws s3 sync --delete build/ $S3_BUCKET
