# From tutorial here
# https://medium.freecodecamp.org/how-to-continuously-deploy-a-static-website-in-style-using-github-and-aws-3df7ecb58d9c

version: 0.2
phases:
  install:
    commands:
      - echo "install step"
      - npm install
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - echo "build step"
      - npm run build
  post_build:
    commands:
      - echo "post_build step"
      - printenv
      - aws s3 sync --delete build/ $S3_BUCKET
      - aws lambda invoke --function-name arn:aws:lambda:us-east-2:401180085381:function:invalidate_CF_from_S3 --payload '{"key":"$S3_BUCKET"}' --log-type Tail out
