# From tutorial here
# https://medium.freecodecamp.org/how-to-continuously-deploy-a-static-website-in-style-using-github-and-aws-3df7ecb58d9c

version: 0.2
phases:
  install:
    commands:
      - echo "install step"
      - npm install
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - echo "build step"
      - npm run build
  post_build:
    commands:
      - echo "post_build step"
      - printenv
      - aws s3 sync --delete build/ $S3_BUCKET --cache-control max-age=31536000,public
      - aws s3 cp $S3_BUCKET/service-worker.js $S3_BUCKET/service-worker.js --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate
      - aws s3 cp $S3_BUCKET/index.html $S3_BUCKET/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate
      - aws lambda invoke --function-name arn:aws:lambda:us-east-2:401180085381:function:invalidate_CF_from_S3 --payload $INVALIDATE_PAYLOAD --log-type Tail out
