services:
  codepost-frontend:
    container_name: codepost-ui
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=https://api.codepost.io
    volumes:
      - certs:/etc/ssl/certs/:ro
    ports:
      - '80:80'
      - '443:443'
