services:
  codepost-frontend:
    container_name: codepost-ui
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    volumes:
      - ./certs:/etc/ssl/certs/:ro
    ports:
      - "443:443"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
