events {}

http {
    server {
        include       mime.types;
        default_type  application/octet-stream;
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";


        listen 443 ssl;
        server_name codepost-frontend;

        ssl_certificate     /etc/ssl/certs/fullchain.pem;
        ssl_certificate_key /etc/ssl/certs/privkey.pem;

        root /usr/share/nginx/html;
        index index.html;
        error_page 404 /index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

    }
    server {
        listen 80;
        server_name codepost-frontend;

        return 301 https://$host$request_uri;
    }
}
