// Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
/* tslint:disable */
/* eslint-disable */
/**
 * codePost API
 *  An API for administrators to mine course data and automate common tasks.  ## Quick Start  ### Installation  ```bash pip install git+https://github.com/rutgers-lcsr/codepost-python.git ```  ### Basic Usage  ```python import codepost_api_client as codepost  # Configure the client config = codepost.Configuration(     host=\"https://codepost-api.cs.rutgers.edu\",     api_key={\"tokenAuth\": \"Token YOUR_API_KEY\"} )  # Use the API with codepost.ApiClient(config) as client:     courses_api = codepost.CoursesApi(client)     assignments_api = codepost.AssignmentsApi(client)          # 1. List all courses     print(\"--- Courses ---\")     courses = courses_api.courses_list()     for course in courses:         print(f\"ID: {course.id} | {course.name} ({course.period})\")              if courses:         my_course_id = courses[0].id                  # 2. List assignments for a course         # Note: Course object contains list of assignment IDs         course_data = courses_api.courses_retrieve(my_course_id)                  print(f\"--- Assignments for Course {my_course_id} ---\")         for assignment_id in course_data.assignments:             # Fetch full assignment details             assignment = assignments_api.assignments_retrieve(assignment_id)             print(f\"ID: {assignment.id} | {assignment.name}\")      # 3. Create a new Course     new_course = codepost.Course(name=\"CS101\", period=\"Fall 2026\")     created_course = courses_api.courses_create(new_course)     print(f\"Created Course: {created_course.id}\")      # 4. Create an Assignment     new_assignment = codepost.Assignment(         name=\"Homework 1\",          course=created_course.id     )     created_assignment = assignments_api.assignments_create(new_assignment) ```  See the [Python SDK Repository](https://github.com/rutgers-lcsr/codepost-python) for more examples.
 *
 * The version of the OpenAPI document: 3.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { CheckSSOAvailabilityResponse } from '../models/index';

export interface SsoCallbackRetrieveRequest {
  provider: string;
}

export interface SsoLoginRetrieveRequest {
  provider: string;
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI {
  /**
   * Handles the callback from the SSO provider. Validates ticket/code, creates session, redirects to frontend.
   */
  async ssoCallbackRetrieveRaw(
    requestParameters: SsoCallbackRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['provider'] == null) {
      throw new runtime.RequiredError(
        'provider',
        'Required parameter "provider" was null or undefined when calling ssoCallbackRetrieve().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/auth/sso/callback/{provider}/`;
    urlPath = urlPath.replace(`{${'provider'}}`, encodeURIComponent(String(requestParameters['provider'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Handles the callback from the SSO provider. Validates ticket/code, creates session, redirects to frontend.
   */
  async ssoCallbackRetrieve(
    requestParameters: SsoCallbackRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.ssoCallbackRetrieveRaw(requestParameters, initOverrides);
  }

  /**
   * Checks if the given email belongs to an SSO-enabled organization. Returns { \"sso_enabled\": true, \"provider\": \"CAS\", \"org_id\": 123 } or { \"sso_enabled\": false }
   */
  async ssoCheckRetrieveRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CheckSSOAvailabilityResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/auth/sso/check/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Checks if the given email belongs to an SSO-enabled organization. Returns { \"sso_enabled\": true, \"provider\": \"CAS\", \"org_id\": 123 } or { \"sso_enabled\": false }
   */
  async ssoCheckRetrieve(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CheckSSOAvailabilityResponse> {
    const response = await this.ssoCheckRetrieveRaw(initOverrides);
    return await response.value();
  }

  /**
   * Redirects user to the SSO provider\'s login page. Requires \'email\' query param to identify the organization (and thus the config), OR \'org\' ID directly.
   */
  async ssoLoginRetrieveRaw(
    requestParameters: SsoLoginRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['provider'] == null) {
      throw new runtime.RequiredError(
        'provider',
        'Required parameter "provider" was null or undefined when calling ssoLoginRetrieve().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/auth/sso/login/{provider}/`;
    urlPath = urlPath.replace(`{${'provider'}}`, encodeURIComponent(String(requestParameters['provider'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Redirects user to the SSO provider\'s login page. Requires \'email\' query param to identify the organization (and thus the config), OR \'org\' ID directly.
   */
  async ssoLoginRetrieve(
    requestParameters: SsoLoginRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.ssoLoginRetrieveRaw(requestParameters, initOverrides);
  }
}
