// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * codePost API
 *  An API for administrators to mine course data and automate common tasks.  ## Quick Start  ### Installation  ```bash pip install git+https://github.com/rutgers-lcsr/codepost-python.git ```  ### Basic Usage  ```python import codepost_api_client as codepost  # Configure the client config = codepost.Configuration(     host=\"https://codepost-api.cs.rutgers.edu\",     api_key={\"tokenAuth\": \"Token YOUR_API_KEY\"} )  # Use the API with codepost.ApiClient(config) as client:     courses_api = codepost.CoursesApi(client)     assignments_api = codepost.AssignmentsApi(client)          # 1. List all courses     print(\"--- Courses ---\")     courses = courses_api.courses_list()     for course in courses:         print(f\"ID: {course.id} | {course.name} ({course.period})\")              if courses:         my_course_id = courses[0].id                  # 2. List assignments for a course         # Note: Course object contains list of assignment IDs         course_data = courses_api.courses_retrieve(my_course_id)                  print(f\"--- Assignments for Course {my_course_id} ---\")         for assignment_id in course_data.assignments:             # Fetch full assignment details             assignment = assignments_api.assignments_retrieve(assignment_id)             print(f\"ID: {assignment.id} | {assignment.name}\")      # 3. Create a new Course     new_course = codepost.Course(name=\"CS101\", period=\"Fall 2026\")     created_course = courses_api.courses_create(new_course)     print(f\"Created Course: {created_course.id}\")      # 4. Create an Assignment     new_assignment = codepost.Assignment(         name=\"Homework 1\",          course=created_course.id     )     created_assignment = assignments_api.assignments_create(new_assignment) ```  See the [Python SDK Repository](https://github.com/rutgers-lcsr/codepost-python) for more examples. 
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AIProviderModelsList,
  AIUsageSummary,
  Course,
  CourseAISettings,
  CourseRoster,
  CourseRosterMap,
  CourseSettings,
  CourseStudentCaptions,
  PaginatedSectionList,
  PatchedCourse,
  PatchedCourseAISettings,
  PatchedCourseRosterMap,
  PatchedCourseStudentCaptions,
} from '../models/index';

export interface AddToRosterPartialUpdateRequest {
    id: number;
    patchedCourse?: Omit<PatchedCourse, 'id'|'assignments'|'sections'|'inviteCode'|'webhooks'|'studentCount'|'isRubricEditor'>;
}

export interface AiModelsRetrieveRequest {
    id: number;
}

export interface AiSettingsPartialUpdateRequest {
    id: number;
    patchedCourseAISettings?: Omit<PatchedCourseAISettings, 'id'|'aiEnabled'|'aiCommentsEnabled'|'orgAiAvailable'|'hasApiKey'|'apiKeyHint'|'defaultTokenRates'>;
}

export interface AiSettingsRetrieveRequest {
    id: number;
}

export interface AiUsageRetrieveRequest {
    id: number;
    endDate?: string;
    granularity?: AiUsageRetrieveGranularityEnum;
    startDate?: string;
}

export interface ChangeInviteCodePartialUpdateRequest {
    id: number;
    patchedCourse?: Omit<PatchedCourse, 'id'|'assignments'|'sections'|'inviteCode'|'webhooks'|'studentCount'|'isRubricEditor'>;
}

export interface CourseSettingsPartialUpdateRequest {
    id: number;
    patchedCourse?: Omit<PatchedCourse, 'id'|'assignments'|'sections'|'inviteCode'|'webhooks'|'studentCount'|'isRubricEditor'>;
}

export interface CourseSettingsRetrieveRequest {
    id: number;
}

export interface CreateRequest {
    course: Omit<Course, 'id'|'assignments'|'sections'|'inviteCode'|'webhooks'|'studentCount'|'isRubricEditor'>;
}

export interface DeleteRubricCategoryPartialUpdateRequest {
    id: number;
    patchedCourse?: Omit<PatchedCourse, 'id'|'assignments'|'sections'|'inviteCode'|'webhooks'|'studentCount'|'isRubricEditor'>;
}

export interface DestroyRequest {
    id: number;
}

export interface PartialUpdateRequest {
    id: number;
    patchedCourse?: Omit<PatchedCourse, 'id'|'assignments'|'sections'|'inviteCode'|'webhooks'|'studentCount'|'isRubricEditor'>;
}

export interface RemoveFromRosterPartialUpdateRequest {
    id: number;
    patchedCourse?: Omit<PatchedCourse, 'id'|'assignments'|'sections'|'inviteCode'|'webhooks'|'studentCount'|'isRubricEditor'>;
}

export interface RetrieveRequest {
    id: number;
}

export interface RosterMapPartialUpdateRequest {
    id: number;
    patchedCourseRosterMap?: PatchedCourseRosterMap;
}

export interface RosterMapRetrieveRequest {
    id: number;
}

export interface RosterPartialUpdateRequest {
    id: number;
    patchedCourse?: Omit<PatchedCourse, 'id'|'assignments'|'sections'|'inviteCode'|'webhooks'|'studentCount'|'isRubricEditor'>;
}

export interface RosterRetrieveRequest {
    id: number;
}

export interface SectionsListRequest {
    id: number;
    page?: number;
    pageSize?: number;
}

export interface StudentCaptionsPartialUpdateRequest {
    id: number;
    patchedCourseStudentCaptions?: PatchedCourseStudentCaptions;
}

export interface StudentCaptionsRetrieveRequest {
    id: number;
}

export interface UpdateRequest {
    id: number;
    course: Omit<Course, 'id'|'assignments'|'sections'|'inviteCode'|'webhooks'|'studentCount'|'isRubricEditor'>;
}

/**
 * 
 */
export class CoursesApi extends runtime.BaseAPI {

    /**
     * get: Show the roster for a course.  patch: Update the roster for a course.
     */
    async addToRosterPartialUpdateRaw(requestParameters: AddToRosterPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseRoster>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addToRosterPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/addToRoster/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['patchedCourse'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * get: Show the roster for a course.  patch: Update the roster for a course.
     */
    async addToRosterPartialUpdate(requestParameters: AddToRosterPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseRoster> {
        const response = await this.addToRosterPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET: Return curated AI models for the course\'s effective provider. Also queries the provider\'s API for live model listings using the course\'s own credentials or inherited org credentials. Only accessible by course admins.
     */
    async aiModelsRetrieveRaw(requestParameters: AiModelsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AIProviderModelsList>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling aiModelsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/aiModels/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * GET: Return curated AI models for the course\'s effective provider. Also queries the provider\'s API for live model listings using the course\'s own credentials or inherited org credentials. Only accessible by course admins.
     */
    async aiModelsRetrieve(requestParameters: AiModelsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AIProviderModelsList> {
        const response = await this.aiModelsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get: Get AI configuration for the course.  patch: Update AI configuration for the course. Admin-only.
     */
    async aiSettingsPartialUpdateRaw(requestParameters: AiSettingsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseAISettings>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling aiSettingsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/aiSettings/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['patchedCourseAISettings'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * get: Get AI configuration for the course.  patch: Update AI configuration for the course. Admin-only.
     */
    async aiSettingsPartialUpdate(requestParameters: AiSettingsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseAISettings> {
        const response = await this.aiSettingsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get: Get AI configuration for the course.  patch: Update AI configuration for the course. Admin-only.
     */
    async aiSettingsRetrieveRaw(requestParameters: AiSettingsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseAISettings>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling aiSettingsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/aiSettings/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * get: Get AI configuration for the course.  patch: Update AI configuration for the course. Admin-only.
     */
    async aiSettingsRetrieve(requestParameters: AiSettingsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseAISettings> {
        const response = await this.aiSettingsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns AI usage analytics for the course. Includes time-series data and per-assignment breakdown. Only accessible by course admins.
     */
    async aiUsageRetrieveRaw(requestParameters: AiUsageRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AIUsageSummary>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling aiUsageRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['endDate'] != null) {
            queryParameters['endDate'] = requestParameters['endDate'];
        }

        if (requestParameters['granularity'] != null) {
            queryParameters['granularity'] = requestParameters['granularity'];
        }

        if (requestParameters['startDate'] != null) {
            queryParameters['startDate'] = requestParameters['startDate'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/aiUsage/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns AI usage analytics for the course. Includes time-series data and per-assignment breakdown. Only accessible by course admins.
     */
    async aiUsageRetrieve(requestParameters: AiUsageRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AIUsageSummary> {
        const response = await this.aiUsageRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async changeInviteCodePartialUpdateRaw(requestParameters: ChangeInviteCodePartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling changeInviteCodePartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/changeInviteCode/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['patchedCourse'],
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async changeInviteCodePartialUpdate(requestParameters: ChangeInviteCodePartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.changeInviteCodePartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async courseSettingsPartialUpdateRaw(requestParameters: CourseSettingsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseSettings>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling courseSettingsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/courseSettings/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['patchedCourse'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async courseSettingsPartialUpdate(requestParameters: CourseSettingsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseSettings> {
        const response = await this.courseSettingsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async courseSettingsRetrieveRaw(requestParameters: CourseSettingsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseSettings>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling courseSettingsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/courseSettings/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async courseSettingsRetrieve(requestParameters: CourseSettingsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseSettings> {
        const response = await this.courseSettingsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async createRaw(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Course>> {
        if (requestParameters['course'] == null) {
            throw new runtime.RequiredError(
                'course',
                'Required parameter "course" was null or undefined when calling create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['course'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async create(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Course> {
        const response = await this.createRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async deleteRubricCategoryPartialUpdateRaw(requestParameters: DeleteRubricCategoryPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteRubricCategoryPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/deleteRubricCategory/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['patchedCourse'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async deleteRubricCategoryPartialUpdate(requestParameters: DeleteRubricCategoryPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteRubricCategoryPartialUpdateRaw(requestParameters, initOverrides);
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async destroyRaw(requestParameters: DestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling destroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async destroy(requestParameters: DestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.destroyRaw(requestParameters, initOverrides);
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async listRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Course>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async list(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Course>> {
        const response = await this.listRaw(initOverrides);
        return await response.value();
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async partialUpdateRaw(requestParameters: PartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Course>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling partialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['patchedCourse'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async partialUpdate(requestParameters: PartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Course> {
        const response = await this.partialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get: Show the roster for a course.  patch: Update the roster for a course.
     */
    async removeFromRosterPartialUpdateRaw(requestParameters: RemoveFromRosterPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseRoster>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removeFromRosterPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/removeFromRoster/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['patchedCourse'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * get: Show the roster for a course.  patch: Update the roster for a course.
     */
    async removeFromRosterPartialUpdate(requestParameters: RemoveFromRosterPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseRoster> {
        const response = await this.removeFromRosterPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async retrieveRaw(requestParameters: RetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Course>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling retrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async retrieve(requestParameters: RetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Course> {
        const response = await this.retrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async rosterMapPartialUpdateRaw(requestParameters: RosterMapPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseRosterMap>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling rosterMapPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/rosterMap/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['patchedCourseRosterMap'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async rosterMapPartialUpdate(requestParameters: RosterMapPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseRosterMap> {
        const response = await this.rosterMapPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async rosterMapRetrieveRaw(requestParameters: RosterMapRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseRosterMap>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling rosterMapRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/rosterMap/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async rosterMapRetrieve(requestParameters: RosterMapRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseRosterMap> {
        const response = await this.rosterMapRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get: Show the roster for a course.  patch: Update the roster for a course.
     */
    async rosterPartialUpdateRaw(requestParameters: RosterPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseRoster>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling rosterPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/roster/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['patchedCourse'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * get: Show the roster for a course.  patch: Update the roster for a course.
     */
    async rosterPartialUpdate(requestParameters: RosterPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseRoster> {
        const response = await this.rosterPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get: Show the roster for a course.  patch: Update the roster for a course.
     */
    async rosterRetrieveRaw(requestParameters: RosterRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseRoster>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling rosterRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/roster/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * get: Show the roster for a course.  patch: Update the roster for a course.
     */
    async rosterRetrieve(requestParameters: RosterRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseRoster> {
        const response = await this.rosterRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets a paginated list of sections for a course. We use this for performance for large courses to fetch sections in bulk. They\'re rarely used in admin console operations, so it\'s a great candidate to paginate Returns a list of Section objects
     */
    async sectionsListRaw(requestParameters: SectionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedSectionList>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sectionsList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/sections/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Gets a paginated list of sections for a course. We use this for performance for large courses to fetch sections in bulk. They\'re rarely used in admin console operations, so it\'s a great candidate to paginate Returns a list of Section objects
     */
    async sectionsList(requestParameters: SectionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedSectionList> {
        const response = await this.sectionsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async studentCaptionsPartialUpdateRaw(requestParameters: StudentCaptionsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseStudentCaptions>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling studentCaptionsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/studentCaptions/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['patchedCourseStudentCaptions'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async studentCaptionsPartialUpdate(requestParameters: StudentCaptionsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseStudentCaptions> {
        const response = await this.studentCaptionsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async studentCaptionsRetrieveRaw(requestParameters: StudentCaptionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseStudentCaptions>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling studentCaptionsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/studentCaptions/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async studentCaptionsRetrieve(requestParameters: StudentCaptionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseStudentCaptions> {
        const response = await this.studentCaptionsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async updateRaw(requestParameters: UpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Course>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling update().'
            );
        }

        if (requestParameters['course'] == null) {
            throw new runtime.RequiredError(
                'course',
                'Required parameter "course" was null or undefined when calling update().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['course'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * list: Return a list of all the courses.  create: Create a new course.  retrieve: Return the given course.  update: Update a course.  partial_update: Update a course.  delete: Delete a course
     */
    async update(requestParameters: UpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Course> {
        const response = await this.updateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum AiUsageRetrieveGranularityEnum {
    Daily = 'daily',
    Hourly = 'hourly',
    Monthly = 'monthly'
}
