// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * codePost API
 *  An API for administrators to mine course data and automate common tasks.  ## Quick Start  ### Installation  ```bash pip install git+https://github.com/rutgers-lcsr/codepost-python.git ```  ### Basic Usage (Python SDK)  ```python from codepost import CodePost, Comment  client = CodePost(api_key=\"YOUR_API_KEY\")  # Create a course with kwargs shorthand course = client.courses.create(name=\"CS101\", period=\"Fall 2026\")  # Create an assignment assignment = client.assignments.create(     name=\"Homework 1\",     course=course.id,     points=100, )  # Create submission + upload files in one call submission = client.submissions.create_with_files(     assignment=assignment.id,     students=[\"student@example.com\"],     files=[         {\"name\": \"main.py\", \"data\": \"print(\'hello\')\", \"extension\": \".py\"},     ], )  # Add inline feedback file_id = client.submissions.retrieve(submission.id).files[0].id client.comments.create(     Comment(         file=file_id,         text=\"Nice work\",         start_line=1,         end_line=1,         point_delta=1,     ) )  # Finalize and export grades client.submissions.bulk_finalize([submission.id], grader=\"ta@example.com\") rows = client.assignments.submissions.export_grades(assignment_id=assignment.id) print(rows[0]) ```  See the [Python SDK Repository](https://github.com/rutgers-lcsr/codepost-python) for more examples.
 *
 * The version of the OpenAPI document: 3.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  AssignmentDeadline,
  DashboardStats,
  PendingAdminActionRequest,
  PendingAdminActionResponse,
  User,
} from '../models/index';

export interface ApprovePendingAdminCreateRequest {
  pendingAdminActionRequest: PendingAdminActionRequest;
}

export interface DenyPendingAdminCreateRequest {
  pendingAdminActionRequest: PendingAdminActionRequest;
}

/**
 *
 */
export class DashboardApi extends runtime.BaseAPI {
  /**
   * Approve a pending admin request (superuser only). Payload: { \'user_email\': \'...\' }
   */
  async approvePendingAdminCreateRaw(
    requestParameters: ApprovePendingAdminCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PendingAdminActionResponse>> {
    if (requestParameters['pendingAdminActionRequest'] == null) {
      throw new runtime.RequiredError(
        'pendingAdminActionRequest',
        'Required parameter "pendingAdminActionRequest" was null or undefined when calling approvePendingAdminCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/dashboard/approve_pending_admin/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['pendingAdminActionRequest'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Approve a pending admin request (superuser only). Payload: { \'user_email\': \'...\' }
   */
  async approvePendingAdminCreate(
    requestParameters: ApprovePendingAdminCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PendingAdminActionResponse> {
    const response = await this.approvePendingAdminCreateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Returns all assignments with their due dates and late upload deadlines. Useful for planning deployment windows.
   */
  async deadlinesListRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<AssignmentDeadline>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/dashboard/deadlines/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Returns all assignments with their due dates and late upload deadlines. Useful for planning deployment windows.
   */
  async deadlinesList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AssignmentDeadline>> {
    const response = await this.deadlinesListRaw(initOverrides);
    return await response.value();
  }

  /**
   * Deny a pending admin request (superuser only). Payload: { \'user_email\': \'...\' }
   */
  async denyPendingAdminCreateRaw(
    requestParameters: DenyPendingAdminCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PendingAdminActionResponse>> {
    if (requestParameters['pendingAdminActionRequest'] == null) {
      throw new runtime.RequiredError(
        'pendingAdminActionRequest',
        'Required parameter "pendingAdminActionRequest" was null or undefined when calling denyPendingAdminCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/dashboard/deny_pending_admin/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['pendingAdminActionRequest'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Deny a pending admin request (superuser only). Payload: { \'user_email\': \'...\' }
   */
  async denyPendingAdminCreate(
    requestParameters: DenyPendingAdminCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PendingAdminActionResponse> {
    const response = await this.denyPendingAdminCreateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Returns all users with pendingValidation=True across all organizations. Used by the SuperAdmin dashboard to manage pending admin requests.
   */
  async pendingAdminsListRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<User>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/dashboard/pending_admins/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Returns all users with pendingValidation=True across all organizations. Used by the SuperAdmin dashboard to manage pending admin requests.
   */
  async pendingAdminsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<User>> {
    const response = await this.pendingAdminsListRaw(initOverrides);
    return await response.value();
  }

  /**
   * Returns aggregated platform statistics.
   */
  async statsRetrieveRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<DashboardStats>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/dashboard/stats/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Returns aggregated platform statistics.
   */
  async statsRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DashboardStats> {
    const response = await this.statsRetrieveRaw(initOverrides);
    return await response.value();
  }
}
