// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * codePost API
 *  An API for administrators to mine course data and automate common tasks.  ## Quick Start  ### Installation  ```bash pip install git+https://github.com/rutgers-lcsr/codepost-python.git ```  ### Basic Usage (Python SDK)  ```python from codepost import CodePost, Comment  client = CodePost(api_key=\"YOUR_API_KEY\")  # Create a course with kwargs shorthand course = client.courses.create(name=\"CS101\", period=\"Fall 2026\")  # Create an assignment assignment = client.assignments.create(     name=\"Homework 1\",     course=course.id,     points=100, )  # Create submission + upload files in one call submission = client.submissions.create_with_files(     assignment=assignment.id,     students=[\"student@example.com\"],     files=[         {\"name\": \"main.py\", \"data\": \"print(\'hello\')\", \"extension\": \".py\"},     ], )  # Add inline feedback file_id = client.submissions.retrieve(submission.id).files[0].id client.comments.create(     Comment(         file=file_id,         text=\"Nice work\",         start_line=1,         end_line=1,         point_delta=1,     ) )  # Finalize and export grades client.submissions.bulk_finalize([submission.id], grader=\"ta@example.com\") rows = client.assignments.submissions.export_grades(assignment_id=assignment.id) print(rows[0]) ```  See the [Python SDK Repository](https://github.com/rutgers-lcsr/codepost-python) for more examples.
 *
 * The version of the OpenAPI document: 3.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ModelFile, PatchedFile } from '../models/index';

export interface CreateRequest {
  modelFile: Omit<ModelFile, 'id' | 'created' | 'modified'>;
}

export interface DestroyRequest {
  id: number;
}

export interface PartialUpdateRequest {
  id: number;
  patchedFile?: Omit<PatchedFile, 'id' | 'created' | 'modified'>;
}

export interface RetrieveRequest {
  id: number;
}

export interface UpdateRequest {
  id: number;
  modelFile: Omit<ModelFile, 'id' | 'created' | 'modified'>;
}

/**
 *
 */
export class FilesApi extends runtime.BaseAPI {
  /**
   * ViewSet for base File objects.  This handles all file types polymorphically. For specific file types, use the dedicated endpoints: - /submissionFiles/ for SubmissionFile objects - /assignmentFiles/ for AssignmentFile objects - /courseFiles/ for CourseFile objects  list: Return a list of all files (all types).  create: Create a new file.  retrieve: Return the given file.  update: Update a file.  partial_update: Partially update a file.  delete: Delete a file.
   */
  async createRaw(
    requestParameters: CreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['modelFile'] == null) {
      throw new runtime.RequiredError(
        'modelFile',
        'Required parameter "modelFile" was null or undefined when calling create().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/files/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['modelFile'],
      },
      initOverrides,
    );

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   * ViewSet for base File objects.  This handles all file types polymorphically. For specific file types, use the dedicated endpoints: - /submissionFiles/ for SubmissionFile objects - /assignmentFiles/ for AssignmentFile objects - /courseFiles/ for CourseFile objects  list: Return a list of all files (all types).  create: Create a new file.  retrieve: Return the given file.  update: Update a file.  partial_update: Partially update a file.  delete: Delete a file.
   */
  async create(
    requestParameters: CreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.createRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * ViewSet for base File objects.  This handles all file types polymorphically. For specific file types, use the dedicated endpoints: - /submissionFiles/ for SubmissionFile objects - /assignmentFiles/ for AssignmentFile objects - /courseFiles/ for CourseFile objects  list: Return a list of all files (all types).  create: Create a new file.  retrieve: Return the given file.  update: Update a file.  partial_update: Partially update a file.  delete: Delete a file.
   */
  async destroyRaw(
    requestParameters: DestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling destroy().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/files/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * ViewSet for base File objects.  This handles all file types polymorphically. For specific file types, use the dedicated endpoints: - /submissionFiles/ for SubmissionFile objects - /assignmentFiles/ for AssignmentFile objects - /courseFiles/ for CourseFile objects  list: Return a list of all files (all types).  create: Create a new file.  retrieve: Return the given file.  update: Update a file.  partial_update: Partially update a file.  delete: Delete a file.
   */
  async destroy(
    requestParameters: DestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.destroyRaw(requestParameters, initOverrides);
  }

  /**
   * ViewSet for base File objects.  This handles all file types polymorphically. For specific file types, use the dedicated endpoints: - /submissionFiles/ for SubmissionFile objects - /assignmentFiles/ for AssignmentFile objects - /courseFiles/ for CourseFile objects  list: Return a list of all files (all types).  create: Create a new file.  retrieve: Return the given file.  update: Update a file.  partial_update: Partially update a file.  delete: Delete a file.
   */
  async listRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<any>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/files/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * ViewSet for base File objects.  This handles all file types polymorphically. For specific file types, use the dedicated endpoints: - /submissionFiles/ for SubmissionFile objects - /assignmentFiles/ for AssignmentFile objects - /courseFiles/ for CourseFile objects  list: Return a list of all files (all types).  create: Create a new file.  retrieve: Return the given file.  update: Update a file.  partial_update: Partially update a file.  delete: Delete a file.
   */
  async list(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<any>> {
    const response = await this.listRaw(initOverrides);
    return await response.value();
  }

  /**
   * ViewSet for base File objects.  This handles all file types polymorphically. For specific file types, use the dedicated endpoints: - /submissionFiles/ for SubmissionFile objects - /assignmentFiles/ for AssignmentFile objects - /courseFiles/ for CourseFile objects  list: Return a list of all files (all types).  create: Create a new file.  retrieve: Return the given file.  update: Update a file.  partial_update: Partially update a file.  delete: Delete a file.
   */
  async partialUpdateRaw(
    requestParameters: PartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling partialUpdate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/files/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['patchedFile'],
      },
      initOverrides,
    );

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   * ViewSet for base File objects.  This handles all file types polymorphically. For specific file types, use the dedicated endpoints: - /submissionFiles/ for SubmissionFile objects - /assignmentFiles/ for AssignmentFile objects - /courseFiles/ for CourseFile objects  list: Return a list of all files (all types).  create: Create a new file.  retrieve: Return the given file.  update: Update a file.  partial_update: Partially update a file.  delete: Delete a file.
   */
  async partialUpdate(
    requestParameters: PartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.partialUpdateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * ViewSet for base File objects.  This handles all file types polymorphically. For specific file types, use the dedicated endpoints: - /submissionFiles/ for SubmissionFile objects - /assignmentFiles/ for AssignmentFile objects - /courseFiles/ for CourseFile objects  list: Return a list of all files (all types).  create: Create a new file.  retrieve: Return the given file.  update: Update a file.  partial_update: Partially update a file.  delete: Delete a file.
   */
  async retrieveRaw(
    requestParameters: RetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling retrieve().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/files/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   * ViewSet for base File objects.  This handles all file types polymorphically. For specific file types, use the dedicated endpoints: - /submissionFiles/ for SubmissionFile objects - /assignmentFiles/ for AssignmentFile objects - /courseFiles/ for CourseFile objects  list: Return a list of all files (all types).  create: Create a new file.  retrieve: Return the given file.  update: Update a file.  partial_update: Partially update a file.  delete: Delete a file.
   */
  async retrieve(
    requestParameters: RetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.retrieveRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * ViewSet for base File objects.  This handles all file types polymorphically. For specific file types, use the dedicated endpoints: - /submissionFiles/ for SubmissionFile objects - /assignmentFiles/ for AssignmentFile objects - /courseFiles/ for CourseFile objects  list: Return a list of all files (all types).  create: Create a new file.  retrieve: Return the given file.  update: Update a file.  partial_update: Partially update a file.  delete: Delete a file.
   */
  async updateRaw(
    requestParameters: UpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling update().');
    }

    if (requestParameters['modelFile'] == null) {
      throw new runtime.RequiredError(
        'modelFile',
        'Required parameter "modelFile" was null or undefined when calling update().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/files/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['modelFile'],
      },
      initOverrides,
    );

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   * ViewSet for base File objects.  This handles all file types polymorphically. For specific file types, use the dedicated endpoints: - /submissionFiles/ for SubmissionFile objects - /assignmentFiles/ for AssignmentFile objects - /courseFiles/ for CourseFile objects  list: Return a list of all files (all types).  create: Create a new file.  retrieve: Return the given file.  update: Update a file.  partial_update: Partially update a file.  delete: Delete a file.
   */
  async update(
    requestParameters: UpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.updateRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
