// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * codePost API
 *  An API for administrators to mine course data and automate common tasks.  ## Quick Start  ### Installation  ```bash pip install codepost ```  ### Basic Usage (Python SDK)  ```python from codepost import CodePost, Comment  client = CodePost(api_key=\"YOUR_API_KEY\")  # Create a course with kwargs shorthand course = client.courses.create(name=\"CS101\", period=\"Fall 2026\")  # Create an assignment assignment = client.assignments.create(     name=\"Homework 1\",     course=course.id,     points=100, )  # Create submission + upload files in one call submission = client.submissions.create_with_files(     assignment=assignment.id,     students=[\"student@example.com\"],     files=[         {\"name\": \"main.py\", \"data\": \"print(\'hello\')\", \"extension\": \".py\"},     ], )  # Add inline feedback file_id = client.submissions.retrieve(submission.id).files[0].id client.comments.create(     Comment(         file=file_id,         text=\"Nice work\",         start_line=1,         end_line=1,         point_delta=1,     ) )  # Finalize and export grades client.submissions.bulk_finalize([submission.id], grader=\"ta@example.com\") rows = client.assignments.submissions.export_grades(assignment_id=assignment.id) print(rows[0]) ```  See the [Python SDK Repository](https://github.com/rutgers-lcsr/codepost-python) for more examples.
 *
 * The version of the OpenAPI document: 4.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  BankCopyRequest,
  BankQuestionsRequest,
  PatchedQuestion,
  Question,
  QuizSuggestionJob,
  RegenerateSuggestionRequest,
  SuggestedQuizQuestion,
} from '../models/index';

export interface CopyToBankCreateRequest {
  bankCopyRequest: BankCopyRequest;
}

export interface CreateRequest {
  question: Omit<Question, 'id' | 'source' | 'createdBy' | 'metadata'>;
}

export interface DestroyRequest {
  id: number;
}

export interface MoveToBankCreateRequest {
  bankQuestionsRequest: BankQuestionsRequest;
}

export interface PartialUpdateRequest {
  id: number;
  patchedQuestion?: Omit<PatchedQuestion, 'id' | 'source' | 'createdBy' | 'metadata'>;
}

export interface RegenerateSuggestionCreateRequest {
  id: number;
  regenerateSuggestionRequest?: RegenerateSuggestionRequest;
}

export interface RegenerationSuggestionsListRequest {
  id: number;
}

export interface RetrieveRequest {
  id: number;
}

export interface UpdateRequest {
  id: number;
  question: Omit<Question, 'id' | 'source' | 'createdBy' | 'metadata'>;
}

/**
 *
 */
export class QuestionsApi extends runtime.BaseAPI {
  /**
   * Copy the given questions (with their choices) into another bank as new questions.
   */
  async copyToBankCreateRaw(
    requestParameters: CopyToBankCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Question>>> {
    if (requestParameters['bankCopyRequest'] == null) {
      throw new runtime.RequiredError(
        'bankCopyRequest',
        'Required parameter "bankCopyRequest" was null or undefined when calling copyToBankCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/questions/copyToBank/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['bankCopyRequest'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Copy the given questions (with their choices) into another bank as new questions.
   */
  async copyToBankCreate(
    requestParameters: CopyToBankCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Question>> {
    const response = await this.copyToBankCreateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Quiz questions, each living in exactly one bank (with nested, writable choices).
   */
  async createRaw(
    requestParameters: CreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Question>> {
    if (requestParameters['question'] == null) {
      throw new runtime.RequiredError(
        'question',
        'Required parameter "question" was null or undefined when calling create().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/questions/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['question'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Quiz questions, each living in exactly one bank (with nested, writable choices).
   */
  async create(
    requestParameters: CreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Question> {
    const response = await this.createRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Quiz questions, each living in exactly one bank (with nested, writable choices).
   */
  async destroyRaw(
    requestParameters: DestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling destroy().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/questions/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Quiz questions, each living in exactly one bank (with nested, writable choices).
   */
  async destroy(
    requestParameters: DestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.destroyRaw(requestParameters, initOverrides);
  }

  /**
   * Quiz questions, each living in exactly one bank (with nested, writable choices).
   */
  async listRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Question>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/questions/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Quiz questions, each living in exactly one bank (with nested, writable choices).
   */
  async list(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Question>> {
    const response = await this.listRaw(initOverrides);
    return await response.value();
  }

  /**
   * Move the given questions into another bank (re-points each question\'s bank).
   */
  async moveToBankCreateRaw(
    requestParameters: MoveToBankCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Question>>> {
    if (requestParameters['bankQuestionsRequest'] == null) {
      throw new runtime.RequiredError(
        'bankQuestionsRequest',
        'Required parameter "bankQuestionsRequest" was null or undefined when calling moveToBankCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/questions/moveToBank/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['bankQuestionsRequest'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Move the given questions into another bank (re-points each question\'s bank).
   */
  async moveToBankCreate(
    requestParameters: MoveToBankCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Question>> {
    const response = await this.moveToBankCreateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Quiz questions, each living in exactly one bank (with nested, writable choices).
   */
  async partialUpdateRaw(
    requestParameters: PartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Question>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling partialUpdate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/questions/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['patchedQuestion'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Quiz questions, each living in exactly one bank (with nested, writable choices).
   */
  async partialUpdate(
    requestParameters: PartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Question> {
    const response = await this.partialUpdateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Generate a refreshed AI suggestion seeded from this existing question (cross-semester update). The instructor reviews and accepts the suggestion. Returns the generation job to poll via quizSuggestionJobs/{id}/ for status and errors. Returns 403 when the course has the quiz_generation AI feature turned off.
   */
  async regenerateSuggestionCreateRaw(
    requestParameters: RegenerateSuggestionCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<QuizSuggestionJob>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling regenerateSuggestionCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/questions/{id}/regenerateSuggestion/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['regenerateSuggestionRequest'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Generate a refreshed AI suggestion seeded from this existing question (cross-semester update). The instructor reviews and accepts the suggestion. Returns the generation job to poll via quizSuggestionJobs/{id}/ for status and errors. Returns 403 when the course has the quiz_generation AI feature turned off.
   */
  async regenerateSuggestionCreate(
    requestParameters: RegenerateSuggestionCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<QuizSuggestionJob> {
    const response = await this.regenerateSuggestionCreateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Pending AI refresh suggestions seeded from this question (for review/accept).
   */
  async regenerationSuggestionsListRaw(
    requestParameters: RegenerationSuggestionsListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<SuggestedQuizQuestion>>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling regenerationSuggestionsList().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/questions/{id}/regenerationSuggestions/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Pending AI refresh suggestions seeded from this question (for review/accept).
   */
  async regenerationSuggestionsList(
    requestParameters: RegenerationSuggestionsListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<SuggestedQuizQuestion>> {
    const response = await this.regenerationSuggestionsListRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Quiz questions, each living in exactly one bank (with nested, writable choices).
   */
  async retrieveRaw(
    requestParameters: RetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Question>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling retrieve().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/questions/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Quiz questions, each living in exactly one bank (with nested, writable choices).
   */
  async retrieve(
    requestParameters: RetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Question> {
    const response = await this.retrieveRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Quiz questions, each living in exactly one bank (with nested, writable choices).
   */
  async updateRaw(
    requestParameters: UpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Question>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling update().');
    }

    if (requestParameters['question'] == null) {
      throw new runtime.RequiredError(
        'question',
        'Required parameter "question" was null or undefined when calling update().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/questions/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['question'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Quiz questions, each living in exactly one bank (with nested, writable choices).
   */
  async update(
    requestParameters: UpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Question> {
    const response = await this.updateRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
