// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * codePost API
 *  An API for administrators to mine course data and automate common tasks.  ## Quick Start  ### Installation  ```bash pip install codepost ```  ### Basic Usage (Python SDK)  ```python from codepost import CodePost, Comment  client = CodePost(api_key=\"YOUR_API_KEY\")  # Create a course with kwargs shorthand course = client.courses.create(name=\"CS101\", period=\"Fall 2026\")  # Create an assignment assignment = client.assignments.create(     name=\"Homework 1\",     course=course.id,     points=100, )  # Create submission + upload files in one call submission = client.submissions.create_with_files(     assignment=assignment.id,     students=[\"student@example.com\"],     files=[         {\"name\": \"main.py\", \"data\": \"print(\'hello\')\", \"extension\": \".py\"},     ], )  # Add inline feedback file_id = client.submissions.retrieve(submission.id).files[0].id client.comments.create(     Comment(         file=file_id,         text=\"Nice work\",         start_line=1,         end_line=1,         point_delta=1,     ) )  # Finalize and export grades client.submissions.bulk_finalize([submission.id], grader=\"ta@example.com\") rows = client.assignments.submissions.export_grades(assignment_id=assignment.id) print(rows[0]) ```  See the [Python SDK Repository](https://github.com/rutgers-lcsr/codepost-python) for more examples.
 *
 * The version of the OpenAPI document: 4.3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { QuizImage } from '../models/index';

export interface CreateRequest {
  id: number;
  course: number;
  token: string;
  url: string;
  originalName: string;
  contentType: string;
  created: string;
}

export interface DestroyRequest {
  id: number;
}

export interface PartialUpdateRequest {
  id: number;
  id2?: number;
  course?: number;
  token?: string;
  url?: string;
  originalName?: string;
  contentType?: string;
  created?: string;
}

export interface RetrieveRequest {
  id: number;
}

export interface UpdateRequest {
  id: number;
  id2: number;
  course: number;
  token: string;
  url: string;
  originalName: string;
  contentType: string;
  created: string;
}

/**
 *
 */
export class QuizImagesApi extends runtime.BaseAPI {
  /**
   * Instructor-uploaded images for quiz/question/bank Markdown descriptions.
   */
  async createRaw(
    requestParameters: CreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<QuizImage>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling create().');
    }

    if (requestParameters['course'] == null) {
      throw new runtime.RequiredError(
        'course',
        'Required parameter "course" was null or undefined when calling create().',
      );
    }

    if (requestParameters['token'] == null) {
      throw new runtime.RequiredError(
        'token',
        'Required parameter "token" was null or undefined when calling create().',
      );
    }

    if (requestParameters['url'] == null) {
      throw new runtime.RequiredError('url', 'Required parameter "url" was null or undefined when calling create().');
    }

    if (requestParameters['originalName'] == null) {
      throw new runtime.RequiredError(
        'originalName',
        'Required parameter "originalName" was null or undefined when calling create().',
      );
    }

    if (requestParameters['contentType'] == null) {
      throw new runtime.RequiredError(
        'contentType',
        'Required parameter "contentType" was null or undefined when calling create().',
      );
    }

    if (requestParameters['created'] == null) {
      throw new runtime.RequiredError(
        'created',
        'Required parameter "created" was null or undefined when calling create().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    const consumes: runtime.Consume[] = [
      { contentType: 'multipart/form-data' },
      { contentType: 'application/x-www-form-urlencoded' },
    ];
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes);

    let formParams: { append(param: string, value: any): any };
    let useForm = false;
    if (useForm) {
      formParams = new FormData();
    } else {
      formParams = new URLSearchParams();
    }

    if (requestParameters['id'] != null) {
      formParams.append('id', requestParameters['id'] as any);
    }

    if (requestParameters['course'] != null) {
      formParams.append('course', requestParameters['course'] as any);
    }

    if (requestParameters['token'] != null) {
      formParams.append('token', requestParameters['token'] as any);
    }

    if (requestParameters['url'] != null) {
      formParams.append('url', requestParameters['url'] as any);
    }

    if (requestParameters['originalName'] != null) {
      formParams.append('originalName', requestParameters['originalName'] as any);
    }

    if (requestParameters['contentType'] != null) {
      formParams.append('contentType', requestParameters['contentType'] as any);
    }

    if (requestParameters['created'] != null) {
      formParams.append('created', requestParameters['created'] as any);
    }

    let urlPath = `/quizImages/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Instructor-uploaded images for quiz/question/bank Markdown descriptions.
   */
  async create(
    requestParameters: CreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<QuizImage> {
    const response = await this.createRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Instructor-uploaded images for quiz/question/bank Markdown descriptions.
   */
  async destroyRaw(
    requestParameters: DestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling destroy().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/quizImages/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Instructor-uploaded images for quiz/question/bank Markdown descriptions.
   */
  async destroy(
    requestParameters: DestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.destroyRaw(requestParameters, initOverrides);
  }

  /**
   * Instructor-uploaded images for quiz/question/bank Markdown descriptions.
   */
  async listRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<QuizImage>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/quizImages/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Instructor-uploaded images for quiz/question/bank Markdown descriptions.
   */
  async list(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<QuizImage>> {
    const response = await this.listRaw(initOverrides);
    return await response.value();
  }

  /**
   * Instructor-uploaded images for quiz/question/bank Markdown descriptions.
   */
  async partialUpdateRaw(
    requestParameters: PartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<QuizImage>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling partialUpdate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    const consumes: runtime.Consume[] = [
      { contentType: 'multipart/form-data' },
      { contentType: 'application/x-www-form-urlencoded' },
    ];
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes);

    let formParams: { append(param: string, value: any): any };
    let useForm = false;
    if (useForm) {
      formParams = new FormData();
    } else {
      formParams = new URLSearchParams();
    }

    if (requestParameters['id2'] != null) {
      formParams.append('id', requestParameters['id2'] as any);
    }

    if (requestParameters['course'] != null) {
      formParams.append('course', requestParameters['course'] as any);
    }

    if (requestParameters['token'] != null) {
      formParams.append('token', requestParameters['token'] as any);
    }

    if (requestParameters['url'] != null) {
      formParams.append('url', requestParameters['url'] as any);
    }

    if (requestParameters['originalName'] != null) {
      formParams.append('originalName', requestParameters['originalName'] as any);
    }

    if (requestParameters['contentType'] != null) {
      formParams.append('contentType', requestParameters['contentType'] as any);
    }

    if (requestParameters['created'] != null) {
      formParams.append('created', requestParameters['created'] as any);
    }

    let urlPath = `/quizImages/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Instructor-uploaded images for quiz/question/bank Markdown descriptions.
   */
  async partialUpdate(
    requestParameters: PartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<QuizImage> {
    const response = await this.partialUpdateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Instructor-uploaded images for quiz/question/bank Markdown descriptions.
   */
  async retrieveRaw(
    requestParameters: RetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<QuizImage>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling retrieve().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/quizImages/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Instructor-uploaded images for quiz/question/bank Markdown descriptions.
   */
  async retrieve(
    requestParameters: RetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<QuizImage> {
    const response = await this.retrieveRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Instructor-uploaded images for quiz/question/bank Markdown descriptions.
   */
  async updateRaw(
    requestParameters: UpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<QuizImage>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling update().');
    }

    if (requestParameters['id2'] == null) {
      throw new runtime.RequiredError('id2', 'Required parameter "id2" was null or undefined when calling update().');
    }

    if (requestParameters['course'] == null) {
      throw new runtime.RequiredError(
        'course',
        'Required parameter "course" was null or undefined when calling update().',
      );
    }

    if (requestParameters['token'] == null) {
      throw new runtime.RequiredError(
        'token',
        'Required parameter "token" was null or undefined when calling update().',
      );
    }

    if (requestParameters['url'] == null) {
      throw new runtime.RequiredError('url', 'Required parameter "url" was null or undefined when calling update().');
    }

    if (requestParameters['originalName'] == null) {
      throw new runtime.RequiredError(
        'originalName',
        'Required parameter "originalName" was null or undefined when calling update().',
      );
    }

    if (requestParameters['contentType'] == null) {
      throw new runtime.RequiredError(
        'contentType',
        'Required parameter "contentType" was null or undefined when calling update().',
      );
    }

    if (requestParameters['created'] == null) {
      throw new runtime.RequiredError(
        'created',
        'Required parameter "created" was null or undefined when calling update().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    const consumes: runtime.Consume[] = [
      { contentType: 'multipart/form-data' },
      { contentType: 'application/x-www-form-urlencoded' },
    ];
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes);

    let formParams: { append(param: string, value: any): any };
    let useForm = false;
    if (useForm) {
      formParams = new FormData();
    } else {
      formParams = new URLSearchParams();
    }

    if (requestParameters['id2'] != null) {
      formParams.append('id', requestParameters['id2'] as any);
    }

    if (requestParameters['course'] != null) {
      formParams.append('course', requestParameters['course'] as any);
    }

    if (requestParameters['token'] != null) {
      formParams.append('token', requestParameters['token'] as any);
    }

    if (requestParameters['url'] != null) {
      formParams.append('url', requestParameters['url'] as any);
    }

    if (requestParameters['originalName'] != null) {
      formParams.append('originalName', requestParameters['originalName'] as any);
    }

    if (requestParameters['contentType'] != null) {
      formParams.append('contentType', requestParameters['contentType'] as any);
    }

    if (requestParameters['created'] != null) {
      formParams.append('created', requestParameters['created'] as any);
    }

    let urlPath = `/quizImages/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Instructor-uploaded images for quiz/question/bank Markdown descriptions.
   */
  async update(
    requestParameters: UpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<QuizImage> {
    const response = await this.updateRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
