// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * codePost API
 *  An API for administrators to mine course data and automate common tasks.  ## Quick Start  ### Installation  ```bash pip install codepost ```  ### Basic Usage (Python SDK)  ```python from codepost import CodePost, Comment  client = CodePost(api_key=\"YOUR_API_KEY\")  # Create a course with kwargs shorthand course = client.courses.create(name=\"CS101\", period=\"Fall 2026\")  # Create an assignment assignment = client.assignments.create(     name=\"Homework 1\",     course=course.id,     points=100, )  # Create submission + upload files in one call submission = client.submissions.create_with_files(     assignment=assignment.id,     students=[\"student@example.com\"],     files=[         {\"name\": \"main.py\", \"data\": \"print(\'hello\')\", \"extension\": \".py\"},     ], )  # Add inline feedback file_id = client.submissions.retrieve(submission.id).files[0].id client.comments.create(     Comment(         file=file_id,         text=\"Nice work\",         start_line=1,         end_line=1,         point_delta=1,     ) )  # Finalize and export grades client.submissions.bulk_finalize([submission.id], grader=\"ta@example.com\") rows = client.assignments.submissions.export_grades(assignment_id=assignment.id) print(rows[0]) ```  See the [Python SDK Repository](https://github.com/rutgers-lcsr/codepost-python) for more examples.
 *
 * The version of the OpenAPI document: 4.3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  GradeQuizResponseRequest,
  PatchedSaveQuizAnswerRequest,
  ReopenQuizResponseRequest,
  RunQuizResponseCodeRequest,
  SebLaunchRequest,
  SebLaunchResponse,
  SetOfficialAttemptRequest,
  StaffQuizAttempt,
  StartQuizAttemptRequest,
  StudentQuiz,
  StudentQuizAttempt,
  StudentQuizResponse,
} from '../models/index';

export interface AvailableQuizzesListRequest {
  course: number;
}

export interface CreateRequest {
  startQuizAttemptRequest: StartQuizAttemptRequest;
}

export interface GradeResponseCreateRequest {
  id: number;
  gradeQuizResponseRequest: GradeQuizResponseRequest;
}

export interface MyAttemptsListRequest {
  quiz: number;
}

export interface ReopenResponseCreateRequest {
  id: number;
  reopenQuizResponseRequest: ReopenQuizResponseRequest;
}

export interface RetrieveRequest {
  id: number;
}

export interface RunCodeCreateRequest {
  id: number;
  runQuizResponseCodeRequest: RunQuizResponseCodeRequest;
}

export interface SaveAnswerPartialUpdateRequest {
  id: number;
  patchedSaveQuizAnswerRequest?: PatchedSaveQuizAnswerRequest;
}

export interface SebLaunchCreateRequest {
  sebLaunchRequest: SebLaunchRequest;
}

export interface SetOfficialCreateRequest {
  id: number;
  setOfficialAttemptRequest?: SetOfficialAttemptRequest;
}

export interface SubmitCreateRequest {
  id: number;
}

/**
 *
 */
export class QuizAttemptsApi extends runtime.BaseAPI {
  /**
   * Published quizzes in ``course`` the caller should see.  Attached quizzes surface once their assignment is released — even while the quiz itself is still locked — so the assignment card can show them with a reason. Standalone quizzes surface only when open now or already attempted.
   */
  async availableQuizzesListRaw(
    requestParameters: AvailableQuizzesListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<StudentQuiz>>> {
    if (requestParameters['course'] == null) {
      throw new runtime.RequiredError(
        'course',
        'Required parameter "course" was null or undefined when calling availableQuizzesList().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['course'] != null) {
      queryParameters['course'] = requestParameters['course'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/quizAttempts/availableQuizzes/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Published quizzes in ``course`` the caller should see.  Attached quizzes surface once their assignment is released — even while the quiz itself is still locked — so the assignment card can show them with a reason. Standalone quizzes surface only when open now or already attempted.
   */
  async availableQuizzesList(
    requestParameters: AvailableQuizzesListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<StudentQuiz>> {
    const response = await this.availableQuizzesListRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Start a new attempt, or resume the student\'s in-progress one, for ``quiz``.  A late student whose quiz has closed may pass ``accessCode`` to start anyway: a match on the quiz\'s access code bypasses the close (only), and the attempt keeps its full time limit.
   */
  async createRaw(
    requestParameters: CreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StudentQuizAttempt>> {
    if (requestParameters['startQuizAttemptRequest'] == null) {
      throw new runtime.RequiredError(
        'startQuizAttemptRequest',
        'Required parameter "startQuizAttemptRequest" was null or undefined when calling create().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/quizAttempts/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['startQuizAttemptRequest'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Start a new attempt, or resume the student\'s in-progress one, for ``quiz``.  A late student whose quiz has closed may pass ``accessCode`` to start anyway: a match on the quiz\'s access code bypasses the close (only), and the attempt keeps its full time limit.
   */
  async create(
    requestParameters: CreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StudentQuizAttempt> {
    const response = await this.createRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Manually grade one essay/code response (quiz graders and course admins only — gated by QuizAttemptPermissions). Recomputes the attempt\'s score and pass state.
   */
  async gradeResponseCreateRaw(
    requestParameters: GradeResponseCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StaffQuizAttempt>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling gradeResponseCreate().',
      );
    }

    if (requestParameters['gradeQuizResponseRequest'] == null) {
      throw new runtime.RequiredError(
        'gradeQuizResponseRequest',
        'Required parameter "gradeQuizResponseRequest" was null or undefined when calling gradeResponseCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/quizAttempts/{id}/gradeResponse/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['gradeQuizResponseRequest'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Manually grade one essay/code response (quiz graders and course admins only — gated by QuizAttemptPermissions). Recomputes the attempt\'s score and pass state.
   */
  async gradeResponseCreate(
    requestParameters: GradeResponseCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StaffQuizAttempt> {
    const response = await this.gradeResponseCreateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * The calling student\'s attempts for ``quiz``.
   */
  async myAttemptsListRaw(
    requestParameters: MyAttemptsListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<StudentQuizAttempt>>> {
    if (requestParameters['quiz'] == null) {
      throw new runtime.RequiredError(
        'quiz',
        'Required parameter "quiz" was null or undefined when calling myAttemptsList().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['quiz'] != null) {
      queryParameters['quiz'] = requestParameters['quiz'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/quizAttempts/myAttempts/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * The calling student\'s attempts for ``quiz``.
   */
  async myAttemptsList(
    requestParameters: MyAttemptsListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<StudentQuizAttempt>> {
    const response = await this.myAttemptsListRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Send a manually graded essay/code response back to the grading queue (undo the grade). The feedback text is kept as a draft; the attempt\'s totals are refreshed.
   */
  async reopenResponseCreateRaw(
    requestParameters: ReopenResponseCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StaffQuizAttempt>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling reopenResponseCreate().',
      );
    }

    if (requestParameters['reopenQuizResponseRequest'] == null) {
      throw new runtime.RequiredError(
        'reopenQuizResponseRequest',
        'Required parameter "reopenQuizResponseRequest" was null or undefined when calling reopenResponseCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/quizAttempts/{id}/reopenResponse/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['reopenQuizResponseRequest'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Send a manually graded essay/code response back to the grading queue (undo the grade). The feedback text is kept as a draft; the attempt\'s totals are refreshed.
   */
  async reopenResponseCreate(
    requestParameters: ReopenResponseCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StaffQuizAttempt> {
    const response = await this.reopenResponseCreateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * A student\'s quiz attempts. Students operate only on their own; staff may read.
   */
  async retrieveRaw(
    requestParameters: RetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StaffQuizAttempt>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling retrieve().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/quizAttempts/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * A student\'s quiz attempts. Students operate only on their own; staff may read.
   */
  async retrieve(
    requestParameters: RetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StaffQuizAttempt> {
    const response = await this.retrieveRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Run a student\'s code answer in the sandbox (quiz graders and course admins only). Dispatches an async execution; poll the attempt to see the result land in the response\'s codeExecution field.
   */
  async runCodeCreateRaw(
    requestParameters: RunCodeCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StaffQuizAttempt>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling runCodeCreate().',
      );
    }

    if (requestParameters['runQuizResponseCodeRequest'] == null) {
      throw new runtime.RequiredError(
        'runQuizResponseCodeRequest',
        'Required parameter "runQuizResponseCodeRequest" was null or undefined when calling runCodeCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/quizAttempts/{id}/runCode/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['runQuizResponseCodeRequest'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Run a student\'s code answer in the sandbox (quiz graders and course admins only). Dispatches an async execution; poll the attempt to see the result land in the response\'s codeExecution field.
   */
  async runCodeCreate(
    requestParameters: RunCodeCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StaffQuizAttempt> {
    const response = await this.runCodeCreateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Autosave a single response within an in-progress, not-yet-expired attempt.
   */
  async saveAnswerPartialUpdateRaw(
    requestParameters: SaveAnswerPartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StudentQuizResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling saveAnswerPartialUpdate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/quizAttempts/{id}/saveAnswer/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['patchedSaveQuizAnswerRequest'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Autosave a single response within an in-progress, not-yet-expired attempt.
   */
  async saveAnswerPartialUpdate(
    requestParameters: SaveAnswerPartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StudentQuizResponse> {
    const response = await this.saveAnswerPartialUpdateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Create a one-click Safe Exam Browser launch for ``quiz``.  Called from the student\'s NORMAL browser (the gate screen): generates a .seb config whose startURL carries a one-time token, so SEB\'s fresh session can authenticate and land on the take route. Returns the seb(s):// URL that opens SEB directly plus the plain config URL as a download fallback.
   */
  async sebLaunchCreateRaw(
    requestParameters: SebLaunchCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SebLaunchResponse>> {
    if (requestParameters['sebLaunchRequest'] == null) {
      throw new runtime.RequiredError(
        'sebLaunchRequest',
        'Required parameter "sebLaunchRequest" was null or undefined when calling sebLaunchCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/quizAttempts/sebLaunch/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['sebLaunchRequest'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Create a one-click Safe Exam Browser launch for ``quiz``.  Called from the student\'s NORMAL browser (the gate screen): generates a .seb config whose startURL carries a one-time token, so SEB\'s fresh session can authenticate and land on the take route. Returns the seb(s):// URL that opens SEB directly plus the plain config URL as a download fallback.
   */
  async sebLaunchCreate(
    requestParameters: SebLaunchCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SebLaunchResponse> {
    const response = await this.sebLaunchCreateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Pin this submitted attempt as the student\'s official score, overriding the quiz\'s scoringPolicy — or unpin with official=false to return to the policy. Quiz graders and course admins only; at most one pin per student.
   */
  async setOfficialCreateRaw(
    requestParameters: SetOfficialCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StaffQuizAttempt>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling setOfficialCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/quizAttempts/{id}/setOfficial/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['setOfficialAttemptRequest'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Pin this submitted attempt as the student\'s official score, overriding the quiz\'s scoringPolicy — or unpin with official=false to return to the policy. Quiz graders and course admins only; at most one pin per student.
   */
  async setOfficialCreate(
    requestParameters: SetOfficialCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StaffQuizAttempt> {
    const response = await this.setOfficialCreateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Finalize and auto-grade the attempt.
   */
  async submitCreateRaw(
    requestParameters: SubmitCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StudentQuizAttempt>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling submitCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/quizAttempts/{id}/submit/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Finalize and auto-grade the attempt.
   */
  async submitCreate(
    requestParameters: SubmitCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StudentQuizAttempt> {
    const response = await this.submitCreateRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
