// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * codePost API
 *  An API for administrators to mine course data and automate common tasks.  ## Quick Start  ### Installation  ```bash pip install git+https://github.com/rutgers-lcsr/codepost-python.git ```  ### Basic Usage (Python SDK)  ```python from codepost import CodePost, Comment  client = CodePost(api_key=\"YOUR_API_KEY\")  # Create a course with kwargs shorthand course = client.courses.create(name=\"CS101\", period=\"Fall 2026\")  # Create an assignment assignment = client.assignments.create(     name=\"Homework 1\",     course=course.id,     points=100, )  # Create submission + upload files in one call submission = client.submissions.create_with_files(     assignment=assignment.id,     students=[\"student@example.com\"],     files=[         {\"name\": \"main.py\", \"data\": \"print(\'hello\')\", \"extension\": \".py\"},     ], )  # Add inline feedback file_id = client.submissions.retrieve(submission.id).files[0].id client.comments.create(     Comment(         file=file_id,         text=\"Nice work\",         start_line=1,         end_line=1,         point_delta=1,     ) )  # Finalize and export grades client.submissions.bulk_finalize([submission.id], grader=\"ta@example.com\") rows = client.assignments.submissions.export_grades(assignment_id=assignment.id) print(rows[0]) ```  See the [Python SDK Repository](https://github.com/rutgers-lcsr/codepost-python) for more examples.
 *
 * The version of the OpenAPI document: 3.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { PatchedSection, Section, Submission } from '../models/index';

export interface CreateRequest {
  section: Omit<Section, 'id'>;
}

export interface DestroyRequest {
  id: number;
}

export interface PartialUpdateRequest {
  id: number;
  patchedSection?: Omit<PatchedSection, 'id'>;
}

export interface RetrieveRequest {
  id: number;
}

export interface SubmissionsListRequest {
  assignment: number;
  id: number;
}

export interface UpdateRequest {
  id: number;
  section: Omit<Section, 'id'>;
}

/**
 *
 */
export class SectionsApi extends runtime.BaseAPI {
  /**
   * list: Return a list of all the sections.  create: Create a new section.  retrieve: Return the given section.  update: Update a section.  partial_update: Update a section.  delete: Delete a section.
   */
  async createRaw(
    requestParameters: CreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Section>> {
    if (requestParameters['section'] == null) {
      throw new runtime.RequiredError(
        'section',
        'Required parameter "section" was null or undefined when calling create().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/sections/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['section'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the sections.  create: Create a new section.  retrieve: Return the given section.  update: Update a section.  partial_update: Update a section.  delete: Delete a section.
   */
  async create(
    requestParameters: CreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Section> {
    const response = await this.createRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the sections.  create: Create a new section.  retrieve: Return the given section.  update: Update a section.  partial_update: Update a section.  delete: Delete a section.
   */
  async destroyRaw(
    requestParameters: DestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling destroy().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/sections/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * list: Return a list of all the sections.  create: Create a new section.  retrieve: Return the given section.  update: Update a section.  partial_update: Update a section.  delete: Delete a section.
   */
  async destroy(
    requestParameters: DestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.destroyRaw(requestParameters, initOverrides);
  }

  /**
   * list: Return a list of all the sections.  create: Create a new section.  retrieve: Return the given section.  update: Update a section.  partial_update: Update a section.  delete: Delete a section.
   */
  async listRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Section>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/sections/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the sections.  create: Create a new section.  retrieve: Return the given section.  update: Update a section.  partial_update: Update a section.  delete: Delete a section.
   */
  async list(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Section>> {
    const response = await this.listRaw(initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the sections.  create: Create a new section.  retrieve: Return the given section.  update: Update a section.  partial_update: Update a section.  delete: Delete a section.
   */
  async partialUpdateRaw(
    requestParameters: PartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Section>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling partialUpdate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/sections/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['patchedSection'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the sections.  create: Create a new section.  retrieve: Return the given section.  update: Update a section.  partial_update: Update a section.  delete: Delete a section.
   */
  async partialUpdate(
    requestParameters: PartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Section> {
    const response = await this.partialUpdateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the sections.  create: Create a new section.  retrieve: Return the given section.  update: Update a section.  partial_update: Update a section.  delete: Delete a section.
   */
  async retrieveRaw(
    requestParameters: RetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Section>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling retrieve().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/sections/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the sections.  create: Create a new section.  retrieve: Return the given section.  update: Update a section.  partial_update: Update a section.  delete: Delete a section.
   */
  async retrieve(
    requestParameters: RetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Section> {
    const response = await this.retrieveRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Grab submissions corresponding to students in a section
   */
  async submissionsListRaw(
    requestParameters: SubmissionsListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Submission>>> {
    if (requestParameters['assignment'] == null) {
      throw new runtime.RequiredError(
        'assignment',
        'Required parameter "assignment" was null or undefined when calling submissionsList().',
      );
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling submissionsList().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['assignment'] != null) {
      queryParameters['assignment'] = requestParameters['assignment'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/sections/{id}/submissions/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Grab submissions corresponding to students in a section
   */
  async submissionsList(
    requestParameters: SubmissionsListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Submission>> {
    const response = await this.submissionsListRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the sections.  create: Create a new section.  retrieve: Return the given section.  update: Update a section.  partial_update: Update a section.  delete: Delete a section.
   */
  async updateRaw(
    requestParameters: UpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Section>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling update().');
    }

    if (requestParameters['section'] == null) {
      throw new runtime.RequiredError(
        'section',
        'Required parameter "section" was null or undefined when calling update().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // courseKeyAuth authentication
    }

    let urlPath = `/sections/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['section'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the sections.  create: Create a new section.  retrieve: Return the given section.  update: Update a section.  partial_update: Update a section.  delete: Delete a section.
   */
  async update(
    requestParameters: UpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Section> {
    const response = await this.updateRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
