// Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
/* tslint:disable */
/* eslint-disable */
/**
 * codePost API
 *  An API for administrators to mine course data and automate common tasks.  ## Quick Start  ### Installation  ```bash pip install git+https://github.com/rutgers-lcsr/codepost-python.git ```  ### Basic Usage  ```python import codepost_api_client as codepost  # Configure the client config = codepost.Configuration(     host=\"https://codepost-api.cs.rutgers.edu\",     api_key={\"tokenAuth\": \"Token YOUR_API_KEY\"} )  # Use the API with codepost.ApiClient(config) as client:     courses_api = codepost.CoursesApi(client)     assignments_api = codepost.AssignmentsApi(client)          # 1. List all courses     print(\"--- Courses ---\")     courses = courses_api.courses_list()     for course in courses:         print(f\"ID: {course.id} | {course.name} ({course.period})\")              if courses:         my_course_id = courses[0].id                  # 2. List assignments for a course         # Note: Course object contains list of assignment IDs         course_data = courses_api.courses_retrieve(my_course_id)                  print(f\"--- Assignments for Course {my_course_id} ---\")         for assignment_id in course_data.assignments:             # Fetch full assignment details             assignment = assignments_api.assignments_retrieve(assignment_id)             print(f\"ID: {assignment.id} | {assignment.name}\")      # 3. Create a new Course     new_course = codepost.Course(name=\"CS101\", period=\"Fall 2026\")     created_course = courses_api.courses_create(new_course)     print(f\"Created Course: {created_course.id}\")      # 4. Create an Assignment     new_assignment = codepost.Assignment(         name=\"Homework 1\",          course=created_course.id     )     created_assignment = assignments_api.assignments_create(new_assignment) ```  See the [Python SDK Repository](https://github.com/rutgers-lcsr/codepost-python) for more examples.
 *
 * The version of the OpenAPI document: 3.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  PatchedSubmission,
  StudentSubmission,
  Submission,
  SubmissionCheckPermissionResponse,
  SubmissionHistory,
  SubmissionPartnerLinkResponse,
  SubmissionTest,
  SubmissionTestResultsResponse,
} from '../models/index';

export interface CheckPermissionRetrieveRequest {
  id: number;
}

export interface CreateRequest {
  submission: Omit<
    Submission,
    | 'id'
    | 'dateEdited'
    | 'grade'
    | 'questionText'
    | 'questionDate'
    | 'responseDate'
    | 'tests'
    | 'testRunsCompleted'
    | 'files'
  >;
}

export interface DeleteRegradePartialUpdateRequest {
  id: number;
  patchedSubmission?: Omit<
    PatchedSubmission,
    | 'id'
    | 'dateEdited'
    | 'grade'
    | 'questionText'
    | 'questionDate'
    | 'responseDate'
    | 'tests'
    | 'testRunsCompleted'
    | 'files'
  >;
}

export interface DestroyRequest {
  id: number;
}

export interface GeneratePartnerLinkRetrieveRequest {
  id: number;
}

export interface HistoryListRequest {
  id: number;
}

export interface HistoryPartialUpdateRequest {
  id: number;
  patchedSubmission?: Omit<
    PatchedSubmission,
    | 'id'
    | 'dateEdited'
    | 'grade'
    | 'questionText'
    | 'questionDate'
    | 'responseDate'
    | 'tests'
    | 'testRunsCompleted'
    | 'files'
  >;
}

export interface NotifyStudentsCreateRequest {
  id: number;
  submission: Omit<
    Submission,
    | 'id'
    | 'dateEdited'
    | 'grade'
    | 'questionText'
    | 'questionDate'
    | 'responseDate'
    | 'tests'
    | 'testRunsCompleted'
    | 'files'
  >;
}

export interface PartialUpdateRequest {
  id: number;
  patchedSubmission?: Omit<
    PatchedSubmission,
    | 'id'
    | 'dateEdited'
    | 'grade'
    | 'questionText'
    | 'questionDate'
    | 'responseDate'
    | 'tests'
    | 'testRunsCompleted'
    | 'files'
  >;
}

export interface RemovePartnerRetrieveRequest {
  id: number;
}

export interface RetrieveRequest {
  id: number;
}

export interface SubmissionTestsListRequest {
  id: number;
}

export interface SubmitRegradePartialUpdateRequest {
  id: number;
  patchedSubmission?: Omit<
    PatchedSubmission,
    | 'id'
    | 'dateEdited'
    | 'grade'
    | 'questionText'
    | 'questionDate'
    | 'responseDate'
    | 'tests'
    | 'testRunsCompleted'
    | 'files'
  >;
}

export interface TestResultsRetrieveRequest {
  id: number;
}

export interface UpdateRequest {
  id: number;
  submission: Omit<
    Submission,
    | 'id'
    | 'dateEdited'
    | 'grade'
    | 'questionText'
    | 'questionDate'
    | 'responseDate'
    | 'tests'
    | 'testRunsCompleted'
    | 'files'
  >;
}

export interface ValidatePartnerLinkAndReturnRetrieveRequest {
  id: number;
  token: string;
}

export interface ValidatePartnerLinkRetrieveRequest {
  id: number;
  token: string;
}

/**
 *
 */
export class SubmissionsApi extends runtime.BaseAPI {
  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async checkPermissionRetrieveRaw(
    requestParameters: CheckPermissionRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SubmissionCheckPermissionResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling checkPermissionRetrieve().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/{id}/checkPermission/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async checkPermissionRetrieve(
    requestParameters: CheckPermissionRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SubmissionCheckPermissionResponse> {
    const response = await this.checkPermissionRetrieveRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async createRaw(
    requestParameters: CreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Submission>> {
    if (requestParameters['submission'] == null) {
      throw new runtime.RequiredError(
        'submission',
        'Required parameter "submission" was null or undefined when calling create().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['submission'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async create(
    requestParameters: CreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Submission> {
    const response = await this.createRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async deleteRegradePartialUpdateRaw(
    requestParameters: DeleteRegradePartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StudentSubmission>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteRegradePartialUpdate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/{id}/deleteRegrade/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['patchedSubmission'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async deleteRegradePartialUpdate(
    requestParameters: DeleteRegradePartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StudentSubmission> {
    const response = await this.deleteRegradePartialUpdateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async destroyRaw(
    requestParameters: DestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling destroy().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async destroy(
    requestParameters: DestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.destroyRaw(requestParameters, initOverrides);
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async generatePartnerLinkRetrieveRaw(
    requestParameters: GeneratePartnerLinkRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SubmissionPartnerLinkResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling generatePartnerLinkRetrieve().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/{id}/generatePartnerLink/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async generatePartnerLinkRetrieve(
    requestParameters: GeneratePartnerLinkRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SubmissionPartnerLinkResponse> {
    const response = await this.generatePartnerLinkRetrieveRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async historyListRaw(
    requestParameters: HistoryListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<SubmissionHistory>>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling historyList().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/{id}/history/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async historyList(
    requestParameters: HistoryListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<SubmissionHistory>> {
    const response = await this.historyListRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async historyPartialUpdateRaw(
    requestParameters: HistoryPartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<SubmissionHistory>>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling historyPartialUpdate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/{id}/history/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['patchedSubmission'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async historyPartialUpdate(
    requestParameters: HistoryPartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<SubmissionHistory>> {
    const response = await this.historyPartialUpdateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async listRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Submission>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async list(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Submission>> {
    const response = await this.listRaw(initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async notifyStudentsCreateRaw(
    requestParameters: NotifyStudentsCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<string>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling notifyStudentsCreate().',
      );
    }

    if (requestParameters['submission'] == null) {
      throw new runtime.RequiredError(
        'submission',
        'Required parameter "submission" was null or undefined when calling notifyStudentsCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/{id}/notifyStudents/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['submission'],
      },
      initOverrides,
    );

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<string>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async notifyStudentsCreate(
    requestParameters: NotifyStudentsCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<string> {
    const response = await this.notifyStudentsCreateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async partialUpdateRaw(
    requestParameters: PartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Submission>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling partialUpdate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['patchedSubmission'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async partialUpdate(
    requestParameters: PartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Submission> {
    const response = await this.partialUpdateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async removePartnerRetrieveRaw(
    requestParameters: RemovePartnerRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<string>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling removePartnerRetrieve().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/{id}/removePartner/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<string>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async removePartnerRetrieve(
    requestParameters: RemovePartnerRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<string> {
    const response = await this.removePartnerRetrieveRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async retrieveRaw(
    requestParameters: RetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Submission>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling retrieve().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async retrieve(
    requestParameters: RetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Submission> {
    const response = await this.retrieveRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async submissionTestsListRaw(
    requestParameters: SubmissionTestsListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<SubmissionTest>>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling submissionTestsList().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/{id}/submissionTests/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async submissionTestsList(
    requestParameters: SubmissionTestsListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<SubmissionTest>> {
    const response = await this.submissionTestsListRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async submitRegradePartialUpdateRaw(
    requestParameters: SubmitRegradePartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StudentSubmission>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling submitRegradePartialUpdate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/{id}/submitRegrade/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['patchedSubmission'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async submitRegradePartialUpdate(
    requestParameters: SubmitRegradePartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StudentSubmission> {
    const response = await this.submitRegradePartialUpdateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async testResultsRetrieveRaw(
    requestParameters: TestResultsRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SubmissionTestResultsResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling testResultsRetrieve().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/{id}/testResults/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async testResultsRetrieve(
    requestParameters: TestResultsRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SubmissionTestResultsResponse> {
    const response = await this.testResultsRetrieveRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async updateRaw(
    requestParameters: UpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Submission>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling update().');
    }

    if (requestParameters['submission'] == null) {
      throw new runtime.RequiredError(
        'submission',
        'Required parameter "submission" was null or undefined when calling update().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/{id}/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['submission'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async update(
    requestParameters: UpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Submission> {
    const response = await this.updateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async validatePartnerLinkAndReturnRetrieveRaw(
    requestParameters: ValidatePartnerLinkAndReturnRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StudentSubmission>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling validatePartnerLinkAndReturnRetrieve().',
      );
    }

    if (requestParameters['token'] == null) {
      throw new runtime.RequiredError(
        'token',
        'Required parameter "token" was null or undefined when calling validatePartnerLinkAndReturnRetrieve().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['token'] != null) {
      queryParameters['token'] = requestParameters['token'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/{id}/validatePartnerLinkAndReturn/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async validatePartnerLinkAndReturnRetrieve(
    requestParameters: ValidatePartnerLinkAndReturnRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StudentSubmission> {
    const response = await this.validatePartnerLinkAndReturnRetrieveRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async validatePartnerLinkRetrieveRaw(
    requestParameters: ValidatePartnerLinkRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<string>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling validatePartnerLinkRetrieve().',
      );
    }

    if (requestParameters['token'] == null) {
      throw new runtime.RequiredError(
        'token',
        'Required parameter "token" was null or undefined when calling validatePartnerLinkRetrieve().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['token'] != null) {
      queryParameters['token'] = requestParameters['token'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] = await this.configuration.apiKey('Authorization'); // tokenAuth authentication
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/submissions/{id}/validatePartnerLink/`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<string>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   * list: Return a list of all the submissions.  create: Create a new submission.  retrieve: Return the given submission.  update: Update a submission.  partial_update: Update a submission.  delete: Delete a submission.
   */
  async validatePartnerLinkRetrieve(
    requestParameters: ValidatePartnerLinkRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<string> {
    const response = await this.validatePartnerLinkRetrieveRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
