// Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
import { Course, Section, User } from '../api-client';

/**
 * The UI consumes `User` from the OpenAPI client/types, which
 * historically included some snake_case fields (e.g. `api_token`, `student_sections`).
 *
 * The autogenerated OpenAPI client may return camelCase variants (e.g. `apiToken`,
 * `studentSections`) depending on the backend/schema.
 *
 * This helper normalizes either shape into the `UserType` shape used across the UI.
 */
export function normalizeUser(raw: unknown): User {
  const user: Record<string, unknown> = raw && typeof raw === 'object' ? { ...(raw as Record<string, unknown>) } : {};

  const apiToken = user['apiToken'] ?? user['api_token'] ?? null;
  const studentSections = user['studentSections'] ?? user['student_sections'] ?? [];

  const normalized: User = {
    id: typeof user['id'] === 'number' ? user['id'] : 0,
    email: typeof user['email'] === 'string' ? user['email'] : undefined,
    password: typeof user['password'] === 'string' ? user['password'] : '',
    organization: typeof user['organization'] === 'number' ? user['organization'] : null,
    studentCourses: Array.isArray(user['studentCourses']) ? (user['studentCourses'] as Course[]) : [],
    graderCourses: Array.isArray(user['graderCourses']) ? (user['graderCourses'] as Course[]) : [],
    superGraderCourses: Array.isArray(user['superGraderCourses']) ? (user['superGraderCourses'] as Course[]) : [],
    courseadminCourses: Array.isArray(user['courseadminCourses']) ? (user['courseadminCourses'] as Course[]) : [],
    leaderSections: Array.isArray(user['leaderSections']) ? (user['leaderSections'] as Section[]) : [],
    codePostAdmin: typeof user['codePostAdmin'] === 'boolean' ? user['codePostAdmin'] : false,
    canCreateCourses: typeof user['canCreateCourses'] === 'boolean' ? user['canCreateCourses'] : false,
    canModifyRosters: typeof user['canModifyRosters'] === 'boolean' ? user['canModifyRosters'] : false,
    isOrgStaff: typeof user['isOrgStaff'] === 'boolean' ? user['isOrgStaff'] : false,
    showProductTips: typeof user['showProductTips'] === 'boolean' ? user['showProductTips'] : false,
    apiToken: typeof apiToken === 'string' ? apiToken : apiToken === null ? null : String(apiToken),
    studentSections: Array.isArray(studentSections) ? (studentSections as number[]) : [],
    hasCredentials: typeof user['hasCredentials'] === 'boolean' ? user['hasCredentials'] : false,
    token: typeof user['token'] === 'string' ? user['token'] : null,
  };

  return normalized;
}
