export const VALID_WEBHOOKS: { [obj: string]: string[] } = {
  course: ['changed', 'name', 'period', 'archived', 'students', 'graders', 'courseAdmins'],
  section: ['added', 'changed', 'removed', 'name'],
  assignment: ['added', 'changed', 'removed', 'name', 'isVisible', 'isReleased', 'explanation', 'points'],
  rubricCategory: ['added', 'changed', 'removed', 'name', 'pointLimit', 'helpText'],
  rubricComment: ['added', 'changed', 'removed', 'text', 'explanation', 'instructionText', 'pointDelta'],
  submission: ['added', 'changed', 'removed', 'grader', 'isFinalized', 'questionIsOpen'],
  file: ['added', 'changed', 'removed', 'code', 'name', 'extension'],
  fileTemplate: ['added', 'changed', 'removed'],
  comment: ['added', 'changed', 'removed', 'text', 'pointDelta', 'rubricComment'],
  testCategory: ['added', 'changed', 'removed'],
  testCase: [
    'added',
    'changed',
    'removed',
    'description',
    'type',
    'pointsFail',
    'pointsPass',
    'text',
    'explanation',
    'exposed',
    'lastSolutionRun',
  ],
  submissionHistory: ['changed'],
  environment: ['added', 'changed', 'removed', 'isRunning'],
  solutionFile: ['added', 'changed', 'removed'],
  helperFile: ['added', 'changed', 'removed'],
};
