// @ts-nocheck
// Auto-generated by scripts/generate_ts_client.sh — do not edit manually.
// Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
import { Configuration, type Middleware } from './runtime';
import { getAuthToken, handleUnauthorized, isTokenExpired, tryRefreshToken } from '../utils/auth';
import {
  AiFeaturesApi,
  AssignmentDataSetsApi,
  AssignmentFilesApi,
  AssignmentsApi,
  AuthApi,
  AutograderApi,
  CapabilitiesApi,
  CommentsApi,
  CommentTemplatesApi,
  CourseFilesApi,
  CoursesApi,
  DashboardApi,
  FilesApi,
  GeneratedQuestionSetsApi,
  GeneratedQuizQuestionsApi,
  ImpersonateApi,
  LearningObjectivesApi,
  LogoutAllApi,
  LogoutApi,
  LogsApi,
  OrganizationsApi,
  OttApi,
  PromptExperimentsApi,
  PromptFeedbackApi,
  PromptTypesApi,
  PromptVariantsApi,
  QuestionBanksApi,
  QuestionsApi,
  QuizAttemptsApi,
  QuizGeneratedSectionsApi,
  QuizImagesApi,
  QuizImportJobsApi,
  QuizQuestionGroupsApi,
  QuizQuestionsApi,
  QuizSuggestionJobsApi,
  QuizzesApi,
  RegistrationApi,
  RubricCategoriesApi,
  RubricCommentsApi,
  SectionsApi,
  StudentDataSetAssignmentsApi,
  SubmissionFilesApi,
  SubmissionsApi,
  SubmissionTestsApi,
  SubscribeApi,
  SuggestedCommentsApi,
  SuggestedQuizQuestionsApi,
  SystemApi,
  TestCasesApi,
  TestCategoriesApi,
  TestCategoryResourcesApi,
  TmpScriptApi,
  TokenAuthApi,
  TokenRefreshApi,
  TokenVerifyApi,
  UsersApi,
  WebhooksApi,
} from './apis';

// Proactively refresh an expired/near-expiry access token BEFORE the request is
// sent, then stamp the (possibly refreshed) token onto the outgoing request.
// This is what keeps an idle/backgrounded tab from 401-ing on return: a wall-clock
// timer can be throttled while the tab is asleep, but this pre-hook always runs on
// the next request, so a dead access token is refreshed instead of rejected.
const authRefreshMiddleware: Middleware = {
  pre: async ({ url, init }) => {
    if (getAuthToken() && isTokenExpired()) {
      await tryRefreshToken();
    }
    const token = getAuthToken();
    if (token && init.headers) {
      (init.headers as Record<string, string>)['Authorization'] = `Bearer ${token}`;
    }
    return { url, init };
  },
};

const unauthorizedMiddleware: Middleware = {
  post: async ({ response }) => {
    if (response.status === 401) {
      await handleUnauthorized();
    }
    return response;
  },
  onError: async ({ response }) => {
    if (response?.status === 401) {
      await handleUnauthorized();
    }
    return response;
  },
};

export const apiClientConfig = new Configuration({
  basePath: process.env.REACT_APP_API_URL,
  accessToken: () => Promise.resolve(getAuthToken()),
  apiKey: () => `Bearer ${getAuthToken()}`,
  middleware: [authRefreshMiddleware, unauthorizedMiddleware],
});

export const aiFeaturesApi = new AiFeaturesApi(apiClientConfig);
export const assignmentDataSetsApi = new AssignmentDataSetsApi(apiClientConfig);
export const assignmentFilesApi = new AssignmentFilesApi(apiClientConfig);
export const assignmentsApi = new AssignmentsApi(apiClientConfig);
export const authApi = new AuthApi(apiClientConfig);
export const autograderApi = new AutograderApi(apiClientConfig);
export const capabilitiesApi = new CapabilitiesApi(apiClientConfig);
export const commentsApi = new CommentsApi(apiClientConfig);
export const commentTemplatesApi = new CommentTemplatesApi(apiClientConfig);
export const courseFilesApi = new CourseFilesApi(apiClientConfig);
export const coursesApi = new CoursesApi(apiClientConfig);
export const dashboardApi = new DashboardApi(apiClientConfig);
export const filesApi = new FilesApi(apiClientConfig);
export const generatedQuestionSetsApi = new GeneratedQuestionSetsApi(apiClientConfig);
export const generatedQuizQuestionsApi = new GeneratedQuizQuestionsApi(apiClientConfig);
export const impersonateApi = new ImpersonateApi(apiClientConfig);
export const learningObjectivesApi = new LearningObjectivesApi(apiClientConfig);
export const logoutAllApi = new LogoutAllApi(apiClientConfig);
export const logoutApi = new LogoutApi(apiClientConfig);
export const logsApi = new LogsApi(apiClientConfig);
export const organizationsApi = new OrganizationsApi(apiClientConfig);
export const ottApi = new OttApi(apiClientConfig);
export const promptExperimentsApi = new PromptExperimentsApi(apiClientConfig);
export const promptFeedbackApi = new PromptFeedbackApi(apiClientConfig);
export const promptTypesApi = new PromptTypesApi(apiClientConfig);
export const promptVariantsApi = new PromptVariantsApi(apiClientConfig);
export const questionBanksApi = new QuestionBanksApi(apiClientConfig);
export const questionsApi = new QuestionsApi(apiClientConfig);
export const quizAttemptsApi = new QuizAttemptsApi(apiClientConfig);
export const quizGeneratedSectionsApi = new QuizGeneratedSectionsApi(apiClientConfig);
export const quizImagesApi = new QuizImagesApi(apiClientConfig);
export const quizImportJobsApi = new QuizImportJobsApi(apiClientConfig);
export const quizQuestionGroupsApi = new QuizQuestionGroupsApi(apiClientConfig);
export const quizQuestionsApi = new QuizQuestionsApi(apiClientConfig);
export const quizSuggestionJobsApi = new QuizSuggestionJobsApi(apiClientConfig);
export const quizzesApi = new QuizzesApi(apiClientConfig);
export const registrationApi = new RegistrationApi(apiClientConfig);
export const rubricCategoriesApi = new RubricCategoriesApi(apiClientConfig);
export const rubricCommentsApi = new RubricCommentsApi(apiClientConfig);
export const sectionsApi = new SectionsApi(apiClientConfig);
export const studentDataSetAssignmentsApi = new StudentDataSetAssignmentsApi(apiClientConfig);
export const submissionFilesApi = new SubmissionFilesApi(apiClientConfig);
export const submissionsApi = new SubmissionsApi(apiClientConfig);
export const submissionTestsApi = new SubmissionTestsApi(apiClientConfig);
export const subscribeApi = new SubscribeApi(apiClientConfig);
export const suggestedCommentsApi = new SuggestedCommentsApi(apiClientConfig);
export const suggestedQuizQuestionsApi = new SuggestedQuizQuestionsApi(apiClientConfig);
export const systemApi = new SystemApi(apiClientConfig);
export const testCasesApi = new TestCasesApi(apiClientConfig);
export const testCategoriesApi = new TestCategoriesApi(apiClientConfig);
export const testCategoryResourcesApi = new TestCategoryResourcesApi(apiClientConfig);
export const tmpScriptApi = new TmpScriptApi(apiClientConfig);
export const tokenAuthApi = new TokenAuthApi(apiClientConfig);
export const tokenRefreshApi = new TokenRefreshApi(apiClientConfig);
export const tokenVerifyApi = new TokenVerifyApi(apiClientConfig);
export const usersApi = new UsersApi(apiClientConfig);
export const webhooksApi = new WebhooksApi(apiClientConfig);
