const universities = [
  {label: "Abilene Christian University (acu.edu)",value: 'acu'},
  {label: "Adelphi University (adelphi.edu)",value: 'adelphi'},
  {label: "Agnes Scott College (scottlan.edu)",value: 'scottlan'},
  {label: "Air Force Institute of Technology (afit.af.mil)",value: 'afit'},
  {label: "Alabama A&M University (aamu.edu)",value: 'aamu'},
  {label: "Alabama State University (alasu.edu)",value: 'alasu'},
  {label: "Alaska Pacific University",value: 'alaska pacific u'},
  {label: "Albertson College of Idaho (acofi.edu)",value: 'acofi'},
  {label: "Albion College (albion.edu)",value: 'albion'},
  {label: "Alderson-Broaddus College",value: 'alderson-broaddu'},
  {label: "Alfred University (alfred.edu)",value: 'alfred'},
  {label: "Allegheny College (alleg.edu)",value: 'alleg'},
  {label: "Allentown College of Saint Francis de Sales (allencol.edu)",value: 'allencol'},
  {label: "Alma College (alma.edu)",value: 'alma'},
  {label: "Alverno College (alverno.edu)",value: 'alverno'},
  {label: "Ambassador University (ambassador.edu)",value: 'ambassador'},
  {label: "American Coastline University (amercoastuniv.edu)",value: 'amercoastuniv'},
  {label: "American Graduate School of International Management (t-bird.edu)",value: 't-bird'},
  {label: "American International College (aic.edu)",value: 'aic'},
  {label: "American University (american.edu)",value: 'american'},
  {label: "Amherst College (amherst.edu)",value: 'amherst'},
  {label: "Andrews University (andrews.edu)",value: 'andrews'},
  {label: "Angelo State University (angelo.edu)",value: 'angelo'},
  {label: "Antioch College (college.antioch.edu)",value: 'college'},
  {label: "Antioch New England (antiochne.edu)",value: 'antiochne'},
  {label: "Antioch University-Los Angeles (antiochla.edu)",value: 'antiochla'},
  {label: "Antioch University-Seattle (seattleantioch.edu)",value: 'seattleantioch'},
  {label: "Appalachian State University (appstate.edu)",value: 'appstate'},
  {label: "Aquinas College (aquinas.edu)",value: 'aquinas'},
  {label: "Arizona State University (asu.edu)",value: 'asu'},
  {label: "Arizona State University East",value: 'arizona state un'},
  {label: "Arizona State University West (west.asu.edu)",value: 'west'},
  {label: "Arizona Western College (awc.cc.az.us)",value: 'awc'},
  {label: "Arkansas State University, Jonesboro (astate.edu)",value: 'astate'},
  {label: "Arkansas Tech University (atu.edu)",value: 'atu'},
  {label: "Armstrong State College (armstrong.edu)",value: 'armstrong'},
  {label: "Ashland University (ashland.edu)",value: 'ashland'},
  {label: "Assumption College (assumption.edu)",value: 'assumption'},
  {label: "Athens State College",value: 'athens state col'},
  {label: "Auburn University (auburn.edu)",value: 'auburn'},
  {label: "Auburn University - Montgomery (aum.edu)",value: 'aum'},
  {label: "Augsburg College (augsburg.edu)",value: 'augsburg'},
  {label: "Augustana College (IL) (augustana.edu)",value: 'augustana'},
  {label: "Augustana College (SD) (augie.edu)",value: 'augie'},
  {label: "Aurora University (aurora.edu)",value: 'aurora'},
  {label: "Austin College (austinc.edu)",value: 'austinc'},
  {label: "Austin Peay State University (apsu.edu)",value: 'apsu'},
  {label: "Averett College (averett.edu)",value: 'averett'},
  {label: "Avila College (avila.edu)",value: 'avila'},
  {label: "Azusa Pacific University (apu.edu)",value: 'apu'},
  {label: "Babson College (babson.edu)",value: 'babson'},
  {label: "Baldwin-Wallace College (baldwinw.edu)",value: 'baldwinw'},
  {label: "Ball State University (bsu.edu)",value: 'bsu'},
  {label: "Baker University (bakeru.edu)",value: 'bakeru'},
  {label: "Baptist Bible College (bbc.edu)",value: 'bbc'},
  {label: "Bard College (bard.edu)",value: 'bard'},
  {label: "Barry University (barry.edu)",value: 'barry'},
  {label: "Bastyr University (bastyr.edu)",value: 'bastyr'},
  {label: "Bates College (bates.edu)",value: 'bates'},
  {label: "Baylor College of Medicine (bcm.tmc.edu)",value: 'bcm'},
  {label: "Baylor University (baylor.edu)",value: 'baylor'},
  {label: "Beaver College (beaver.edu)",value: 'beaver'},
  {label: "Belmont University (belmont.edu)",value: 'belmont'},
  {label: "Beloit College (beloit.edu)",value: 'beloit'},
  {label: "Bemidji State University (bemidji.msus.edu)",value: 'bemidji'},
  {label: "Benedictine College (benedictine.edu)",value: 'benedictine'},
  {label: "Bennington College (bennington.edu)",value: 'bennington'},
  {label: "Bentley College (bentley.edu)",value: 'bentley'},
  {label: "Berea College (berea.edu)",value: 'berea'},
  {label: "Berklee College of Music (berklee.edu)",value: 'berklee'},
  {label: "Bethany College (CA) (bethany.edu)",value: 'bethany'},
  {label: "Bethany College (WV) (bethany.wvnet.edu)",value: 'bethany'},
  {label: "Bethel College (KS) (bethelks.edu)",value: 'bethelks'},
  {label: "Bethel College and Seminary (MN) (bethel.edu)",value: 'bethel'},
  {label: "Biola University (biola.edu)",value: 'biola'},
  {label: "Birmingham-Southern College (bsc.edu)",value: 'bsc'},
  {label: "Black Hills State University (bhsu.edu)",value: 'bhsu'},
  {label: "Bloomsburg University of Pennsylvania (bloomu.edu)",value: 'bloomu'},
  {label: "Bluffton College (bluffton.edu)",value: 'bluffton'},
  {label: "Bob Jones University (bju.edu)",value: 'bju'},
  {label: "Boise State University (idbsu.edu)",value: 'idbsu'},
  {label: "Boston College (bc.edu)",value: 'bc'},
  {label: "Boston Graduate School of Psychoanalysis (bgsp.edu)",value: 'bgsp'},
  {label: "Boston University (bu.edu)",value: 'bu'},
  {label: "Bowdoin College (bowdoin.edu)",value: 'bowdoin'},
  {label: "Bowie State University (bsu.umd.edu)",value: 'bsu'},
  {label: "Bowling Green State University (bgsu.edu)",value: 'bgsu'},
  {label: "Bradley University (bradley.edu)",value: 'bradley'},
  {label: "Brandeis University (brandeis.edu)",value: 'brandeis'},
  {label: "Brenau University (brenau.edu)",value: 'brenau'},
  {label: "Briar Cliff College (briar-cliff.edu)",value: 'briar-cliff'},
  {label: "Bridgewater College (bridgewater.edu)",value: 'bridgewater'},
  {label: "Brigham Young University (byu.edu)",value: 'byu'},
  {label: "Brigham Young University Hawaii (byuh.edu)",value: 'byuh'},
  {label: "Brown University (brown.edu)",value: 'brown'},
  {label: "Bryant College (bryant.edu)",value: 'bryant'},
  {label: "Bryn Mawr College (brynmawr.edu)",value: 'brynmawr'},
  {label: "Bucknell University (bucknell.edu)",value: 'bucknell'},
  {label: "Buena Vista University (bvu.edu)",value: 'bvu'},
  {label: "Butler University (butler.edu)",value: 'butler'},
  {label: "California Coast University (calcoastuniv.edu)",value: 'calcoastuniv'},
  {label: "California Institute of Technology (caltech.edu)",value: 'caltech'},
  {label: "California Lutheran University (callutheran.edu)",value: 'callutheran'},
  {label: "California Maritime Academy (csum.edu)",value: 'csum'},
  {label: "California National University (cnuas.edu)",value: 'cnuas'},
  {label: "California Pacific University",value: 'california pacif'},
  {label: "California Polytechnic State University, San Luis Obispo (calpoly.edu)",value: 'calpoly'},
  {label: "California School of Professional Psychology",value: 'california schoo'},
  {label: "California State Polytechnic University, Pomona (csupomona.edu)",value: 'csupomona'},
  {label: "California State University System (calstate.edu)",value: 'calstate'},
  {label: "California State University, Bakersfield (csubak.edu)",value: 'csubak'},
  {label: "California State University, Chico (csuchico.edu)",value: 'csuchico'},
  {label: "California State University, Dominguez Hills (csudh.edu)",value: 'csudh'},
  {label: "California State University, Fresno (csufresno.edu)",value: 'csufresno'},
  {label: "California State University, Fullerton (fullerton.edu)",value: 'fullerton'},
  {label: "California State University, Hayward (csuhayward.edu)",value: 'csuhayward'},
  {label: "California State University, Long Beach (csulb.edu)",value: 'csulb'},
  {label: "California State University, Los Angeles (calstatela.edu)",value: 'calstatela'},
  {label: "California State University, Monterey Bay (monterey.edu)",value: 'monterey'},
  {label: "California State University, Northridge (csun.edu)",value: 'csun'},
  {label: "California State University, Sacramento (csus.edu)",value: 'csus'},
  {label: "California State University, San Bernardino (csusb.edu)",value: 'csusb'},
  {label: "California State University, San Jose (sjsu.edu)",value: 'sjsu'},
  {label: "California State University, San Marcos (csusm.edu)",value: 'csusm'},
  {label: "California State University, Sacramento (csus.edu)",value: 'csus'},
  {label: "California State University, Stanislaus (csustan.edu)",value: 'csustan'},
  {label: "California University of Pennsylvania (cup.edu)",value: 'cup'},
  {label: "Calvin College (calvin.edu)",value: 'calvin'},
  {label: "Campbell University (campbell.edu)",value: 'campbell'},
  {label: "Campbellsville College (campbellsvil.edu)",value: 'campbellsvil'},
  {label: "Cameron University (cameron.edu)",value: 'cameron'},
  {label: "Canisius College (canisius.edu)",value: 'canisius'},
  {label: "Carleton College (carleton.edu)",value: 'carleton'},
  {label: "Carlow College (carlow.edu)",value: 'carlow'},
  {label: "Carnegie Mellon University (cmu.edu)",value: 'cmu'},
  {label: "Carroll College (MT) (carroll.edu)",value: 'carroll'},
  {label: "Carroll College (WI) (cc.edu)",value: 'cc'},
  {label: "Carson-Newman College (cn.edu)",value: 'cn'},
  {label: "Carthage College (carthage.edu)",value: 'carthage'},
  {label: "Case Western Reserve University (cwru.edu)",value: 'cwru'},
  {label: "Castleton State University (csc.vsc.edu)",value: 'csc'},
  {label: "The Catholic University of America (cua.edu)",value: 'cua'},
  {label: "Cedarville College (cedarville.edu)",value: 'cedarville'},
  {label: "Centenary College of Louisiana (centenary.edu)",value: 'centenary'},
  {label: "Central College (central.edu)",value: 'central'},
  {label: "Central Connecticut State University (ccsu.ctstateu.edu)",value: 'ccsu'},
  {label: "Central Methodist College (cmc.edu)",value: 'cmc'},
  {label: "Central Michigan University (cmich.edu)",value: 'cmich'},
  {label: "Central Missouri State University (cmsu.edu)",value: 'cmsu'},
  {label: "Central Washington University (cwu.edu)",value: 'cwu'},
  {label: "Centre College (centre.edu)",value: 'centre'},
  {label: "Chadron State College (csc.edu)",value: 'csc'},
  {label: "Champlain College (champlain.edu)",value: 'champlain'},
  {label: "Chapman University (chapman.edu)",value: 'chapman'},
  {label: "Chatham College (chatham.edu)",value: 'chatham'},
  {label: "Chesapeake College (chesapeake.edu)",value: 'chesapeake'},
  {label: "Cheyney University (cheyney.edu)",value: 'cheyney'},
  {label: "The Chicago School of Professional Psychology (csopp.edu)",value: 'csopp'},
  {label: "Christian Brothers University (cbu.edu)",value: 'cbu'},
  {label: "Christian Theological Seminary (cts.edu)",value: 'cts'},
  {label: "Christopher Newport University (cnu.edu)",value: 'cnu'},
  {label: "The Citadel (citadel.edu)",value: 'citadel'},
  {label: "City University (cityu.edu)",value: 'cityu'},
  {label: "City University of New York (cuny.edu)",value: 'cuny'},
  {label: "Claremont Graduate School (cgs.edu)",value: 'cgs'},
  {label: "Claremont McKenna College (mckenna.edu)",value: 'mckenna'},
  {label: "Clarion University of Pennsylvania (clarion.edu)",value: 'clarion'},
  {label: "Clark University (clarku.edu)",value: 'clarku'},
  {label: "Clarke College (clarke.edu)",value: 'clarke'},
  {label: "Clarkson University (clarkson.edu)",value: 'clarkson'},
  {label: "Clayton State College (csc.peachnet.edu)",value: 'csc'},
  {label: "Clemson University (clemson.edu)",value: 'clemson'},
  {label: "Cleveland State University (csuohio.edu)",value: 'csuohio'},
  {label: "Clinch Valley College (clinch.edu)",value: 'clinch'},
  {label: "Coastal Carolina University (coastal.edu)",value: 'coastal'},
  {label: "Coe College (coe.edu)",value: 'coe'},
  {label: "Coker College (coker.edu)",value: 'coker'},
  {label: "Colby College (colby.edu)",value: 'colby'},
  {label: "Colgate University (colgate.edu)",value: 'colgate'},
  {label: "College of the Atlantic (coa.edu)",value: 'coa'},
  {label: "College of Charleston (cofc.edu)",value: 'cofc'},
  {label: "College of Eastern Utah (ceu.edu)",value: 'ceu'},
  {label: "College of the Holy Cross (holycross.edu)",value: 'holycross'},
  {label: "College of Saint Benedict (csbsju.edu)",value: 'csbsju'},
  {label: "College of Saint Catherine (stkate.edu)",value: 'stkate'},
  {label: "College of St. Francis (stfrancis.edu)",value: 'stfrancis'},
  {label: "College of Saint Rose (strose.edu)",value: 'strose'},
  {label: "College of St. Scholastica (css.edu)",value: 'css'},
  {label: "College of William and Mary (wm.edu)",value: 'wm'},
  {label: "The College of Wooster (wooster.edu)",value: 'wooster'},
  {label: "Colorado Christian University (ccu.edu)",value: 'ccu'},
  {label: "Colorado College (cc.colorado.edu)",value: 'cc'},
  {label: "Colorado School of Mines (mines.colorado.edu)",value: 'mines'},
  {label: "Colorado State University (colostate.edu)",value: 'colostate'},
  {label: "Columbia College Chicago (colum.edu)",value: 'colum'},
  {label: "Columbia Southern University (colsouth.edu)",value: 'colsouth'},
  {label: "Columbia Union College (cuc.edu)",value: 'cuc'},
  {label: "Columbia University (columbia.edu)",value: 'columbia'},
  {label: "Concordia College-Ann Arbor (ccaa.edu)",value: 'ccaa'},
  {label: "Concordia College-Moorhead (cord.edu)",value: 'cord'},
  {label: "Concordia College-St. Paul (csp.edu)",value: 'csp'},
  {label: "Concordia College-Seward (ccsn.edu)",value: 'ccsn'},
  {label: "Concordia University River Forest, Illinois (cuis.edu)",value: 'cuis'},
  {label: "Connecticut College (conncoll.edu)",value: 'conncoll'},
  {label: "The Cooper Union for the Advancement of Science and Art (cooper.edu)",value: 'cooper'},
  {label: "Coppin State College (coppin.umd.edu)",value: 'coppin'},
  {label: "Cornell College (cornell-iowa.edu)",value: 'cornell-iowa'},
  {label: "Cornell University (cornell.edu)",value: 'cornell'},
  {label: "Cornerstone College",value: 'cornerstone coll'},
  {label: "Creighton University (creighton.edu)",value: 'creighton'},
  {label: "Curry College (curry.edu)",value: 'curry'},
  {label: "Daemen College (daemen.edu)",value: 'daemen'},
  {label: "Dakota State University (dsu.edu)",value: 'dsu'},
  {label: "Dakota Wesleyan University (dwu.edu)",value: 'dwu'},
  {label: "Dallas Baptist University (dbu.edu)",value: 'dbu'},
  {label: "Dana College (dana.edu)",value: 'dana'},
  {label: "Daniel Webster College (dwc.edu)",value: 'dwc'},
  {label: "Dartmouth College (dartmouth.edu)",value: 'dartmouth'},
  {label: "Davenport College Detroit College of Business (davenport.edu)",value: 'davenport'},
  {label: "Davidson College (davidson.edu)",value: 'davidson'},
  {label: "Davis & Elkins College (dne.wvnet.edu)",value: 'dne'},
  {label: "Delaware State University (dsc.edu)",value: 'dsc'},
  {label: "Delta State University (deltast.edu)",value: 'deltast'},
  {label: "Denison University (denison.edu)",value: 'denison'},
  {label: "DePaul University (depaul.edu)",value: 'depaul'},
  {label: "DePauw University (depauw.edu)",value: 'depauw'},
  {label: "DeVry Institute of Technology (devrycols.edu)",value: 'devrycols'},
  {label: "DeVry Institute of Technology-Dallas (devry.edu)",value: 'devry'},
  {label: "DeVry Institute of Technology-Phoenix (devry-phx.edu)",value: 'devry-phx'},
  {label: "Dickinson College (dickinson.edu)",value: 'dickinson'},
  {label: "Dickinson State University (dsu.nodak.edu)",value: 'dsu'},
  {label: "Dillard University (dillard.edu)",value: 'dillard'},
  {label: "Dominican College (dominican.edu)",value: 'dominican'},
  {label: "Dordt College (Dordt.edu)",value: 'Dordt'},
  {label: "Dowling College (dowling.edu)",value: 'dowling'},
  {label: "Drake University (drake.edu)",value: 'drake'},
  {label: "Drew University (drew.edu)",value: 'drew'},
  {label: "Drexel University (drexel.edu)",value: 'drexel'},
  {label: "Drury College (drury.edu)",value: 'drury'},
  {label: "Duke University (duke.edu)",value: 'duke'},
  {label: "Duquesne University (duq.edu)",value: 'duq'},
  {label: "Earlham College (earlham.edu)",value: 'earlham'},
  {label: "East Carolina University (ecu.edu)",value: 'ecu'},
  {label: "East Central University (ecok.edu)",value: 'ecok'},
  {label: "East Stroudsburg State University of Pennsylvania (esu.edu)",value: 'esu'},
  {label: "East Tennessee State University (etsu-tn.edu)",value: 'etsu-tn'},
  {label: "East Texas State University (etsu.edu)",value: 'etsu'},
  {label: "Eastern Connecticut State University (ecsu.ctstateu.edu)",value: 'ecsu'},
  {label: "Eastern Illinois University (eiu.edu)",value: 'eiu'},
  {label: "Eastern Kentucky University (eku.edu)",value: 'eku'},
  {label: "Eastern Mennonite University (emu.edu)",value: 'emu'},
  {label: "Eastern Michigan University (emich.edu)",value: 'emich'},
  {label: "Eastern Nazarene College",value: 'eastern nazarene'},
  {label: "Eastern New Mexico University (enmu.edu)",value: 'enmu'},
  {label: "Eastern Oregon State College (eosc.osshe.edu)",value: 'eosc'},
  {label: "Eastern Washington University (ewu.edu)",value: 'ewu'},
  {label: "Edgewood College (edgewood.edu)",value: 'edgewood'},
  {label: "Edinboro University of Pennsylvania (edinboro.edu)",value: 'edinboro'},
  {label: "Elizabeth City State University (ecsu.edu)",value: 'ecsu'},
  {label: "Elizabethtown College (etown.edu)",value: 'etown'},
  {label: "Elmhurst College (elmhurst.edu)",value: 'elmhurst'},
  {label: "Elon College (elon.edu)",value: 'elon'},
  {label: "Embry-Riddle Aeronautical University, Arizona (erau.edu)",value: 'erau'},
  {label: "Embry-Riddle Aeronautical University, Florida (erau.edu)",value: 'erau'},
  {label: "Emerson College (emerson.edu)",value: 'emerson'},
  {label: "Emmanuel College (emmanuel.edu)",value: 'emmanuel'},
  {label: "Emmaus Bible College",value: 'emmaus bible col'},
  {label: "Emporia State University (emporia.edu)",value: 'emporia'},
  {label: "Emory & Henry College",value: 'emory & henry co'},
  {label: "Emory University (emory.edu)",value: 'emory'},
  {label: "Evergreen State College (evergreen.edu)",value: 'evergreen'},
  {label: "Fairfield University",value: 'fairfield univer'},
  {label: "Fairleigh Dickinson University (fdu.edu)",value: 'fdu'},
  {label: "Fairmont State College (fairmont.wvnet.edu)",value: 'fairmont'},
  {label: "Fayetteville State University (fsufay.edu)",value: 'fsufay'},
  {label: "Ferris State University (ferris.edu)",value: 'ferris'},
  {label: "Fielding Institute (fielding.edu)",value: 'fielding'},
  {label: "Fisk University (fisk.edu)",value: 'fisk'},
  {label: "Fitchburg State College (fsc.edu)",value: 'fsc'},
  {label: "Florida Agricultural and Mechanical University (famu.edu)",value: 'famu'},
  {label: "Florida Atlantic University (fau.edu)",value: 'fau'},
  {label: "Florida Gulf Coast University (fgcu.edu)",value: 'fgcu'},
  {label: "Florida Institute of Technology (fit.edu)",value: 'fit'},
  {label: "Florida International University (fiu.edu)",value: 'fiu'},
  {label: "Florida State University (fsu.edu)",value: 'fsu'},
  {label: "Fontbonne College (fontbonne.edu)",value: 'fontbonne'},
  {label: "Fordham University (fordham.edu)",value: 'fordham'},
  {label: "Fort Hays State University (fhsu.edu)",value: 'fhsu'},
  {label: "Fort Lewis College (fortlewis.edu)",value: 'fortlewis'},
  {label: "Franciscan University",value: 'franciscan unive'},
  {label: "Franklin and Marshall College (fandm.edu)",value: 'fandm'},
  {label: "Franklin Pierce Law Center (fplc.edu)",value: 'fplc'},
  {label: "Franklin University (franklin.edu)",value: 'franklin'},
  {label: "Fresno Pacific University (fresno.edu)",value: 'fresno'},
  {label: "Friends University (friends.edu)",value: 'friends'},
  {label: "Frostburg State University (fsu.umd.edu)",value: 'fsu'},
  {label: "Fuller Theological Seminary (fuller.edu)",value: 'fuller'},
  {label: "Furman University (furman.edu)",value: 'furman'},
  {label: "Gallaudet University (gallaudet.edu)",value: 'gallaudet'},
  {label: "Gannon University (gannon.edu)",value: 'gannon'},
  {label: "Geneva College (geneva.edu)",value: 'geneva'},
  {label: "George Fox College (gfc.edu)",value: 'gfc'},
  {label: "George Mason University (gmu.edu)",value: 'gmu'},
  {label: "George Washington University (gwu.edu)",value: 'gwu'},
  {label: "Georgetown University (georgetown.edu)",value: 'georgetown'},
  {label: "Georgia College (gac.peachnet.edu)",value: 'gac'},
  {label: "Georgia Institute of Technology (gatech.edu)",value: 'gatech'},
  {label: "Georgia Southern University (gasou.edu)",value: 'gasou'},
  {label: "Georgia Southwestern College (gsw.peachnet.edu)",value: 'gsw'},
  {label: "Georgia State University (gsu.edu)",value: 'gsu'},
  {label: "Georgian Court College (georgian.edu)",value: 'georgian'},
  {label: "Gettysburg College (gettysburg.edu)",value: 'gettysburg'},
  {label: "GMI Engineering and Management Institute (gmi.edu)",value: 'gmi'},
  {label: "Golden Gate University (ggu.edu)",value: 'ggu'},
  {label: "Goldey-Beacom College (gbc.edu)",value: 'gbc'},
  {label: "Gonzaga University (gonzaga.edu)",value: 'gonzaga'},
  {label: "Goshen College (goshen.edu)",value: 'goshen'},
  {label: "Goucher College (goucher.edu)",value: 'goucher'},
  {label: "Governors State University (bgu.edu)",value: 'bgu'},
  {label: "Grace College (grace.edu)",value: 'grace'},
  {label: "Graceland College (graceland.edu)",value: 'graceland'},
  {label: "Grand Valley State University (gvsu.edu)",value: 'gvsu'},
  {label: "Greenleaf University (greenleaf.edu)",value: 'greenleaf'},
  {label: "Grinnell College (grin.edu)",value: 'grin'},
  {label: "Guilford College (guilford.edu)",value: 'guilford'},
  {label: "Gustavus Adolphus College (gac.edu)",value: 'gac'},
  {label: "Gutenberg College",value: 'gutenberg colleg'},
  {label: "Hamilton College (hamilton.edu)",value: 'hamilton'},
  {label: "Hamline University (hamline.edu)",value: 'hamline'},
  {label: "Hampden-Sydney College (hsc.edu)",value: 'hsc'},
  {label: "Hampshire College (hampshire.edu)",value: 'hampshire'},
  {label: "Hampton University (hamptonu.edu)",value: 'hamptonu'},
  {label: "Hanover College (hanover.edu)",value: 'hanover'},
  {label: "Harding University (harding.edu)",value: 'harding'},
  {label: "Hartwick College (hartwick.edu)",value: 'hartwick'},
  {label: "Harvard University (harvard.edu)",value: 'harvard'},
  {label: "Harvey Mudd College (hmc.edu)",value: 'hmc'},
  {label: "Haskell Indian Nations University (haskell.edu)",value: 'haskell'},
  {label: "Hastings College (hastings.edu)",value: 'hastings'},
  {label: "Haverford College in Pennsylvania (haverford.edu)",value: 'haverford'},
  {label: "Hawaii Pacific University (hpu.edu)",value: 'hpu'},
  {label: "Heidelberg College (heidelberg.edu)",value: 'heidelberg'},
  {label: "Hendrix College (hendrix.edu)",value: 'hendrix'},
  {label: "Hesston College (hesston.edu)",value: 'hesston'},
  {label: "High Point University (highpoint.edu)",value: 'highpoint'},
  {label: "Hillsdale College (hillsdale.edu)",value: 'hillsdale'},
  {label: "Hiram College (hiram.edu)",value: 'hiram'},
  {label: "Hobart and William Smith Colleges (hws.edu)",value: 'hws'},
  {label: "Hofstra University (hofstra.edu)",value: 'hofstra'},
  {label: "Hollins College (hollins.edu)",value: 'hollins'},
  {label: "Holy Cross College (holycross.edu)",value: 'holycross'},
  {label: "Hood College (hood.edu)",value: 'hood'},
  {label: "Hope College (hope.edu)",value: 'hope'},
  {label: "Howard University (howard.edu)",value: 'howard'},
  {label: "Humboldt State University (humboldt.edu)",value: 'humboldt'},
  {label: "Hunter College (hunter.cuny.edu)",value: 'hunter'},
  {label: "Huntingdon College (huntingdon.edu)",value: 'huntingdon'},
  {label: "Huntington College (huntcol.edu)",value: 'huntcol'},
  {label: "ICI University (ici.edu)",value: 'ici'},
  {label: "Idaho State University (isu.edu)",value: 'isu'},
  {label: "Illinois Benedictine College (ibc.edu)",value: 'ibc'},
  {label: "Illinois Institute of Technology (iit.edu)",value: 'iit'},
  {label: "Illinois State University (ilstu.edu)",value: 'ilstu'},
  {label: "Incarnate Word College (iwctx.edu)",value: 'iwctx'},
  {label: "Indiana Institute of Technology (indtech.edu)",value: 'indtech'},
  {label: "Indiana State University (indstate.edu)",value: 'indstate'},
  {label: "Indiana University System (indiana.edu)",value: 'indiana'},
  {label: "Indiana University/Purdue University at Columbus (columbus.iupui.edu)",value: 'columbus'},
  {label: "Indiana University/Purdue University at Fort Wayne (ipfw.indiana.edu)",value: 'ipfw'},
  {label: "Indiana University/Purdue University at Indianapolis (iupui.edu)",value: 'iupui'},
  {label: "Indiana University at Bloomington (indiana.edu)",value: 'indiana'},
  {label: "Indiana University at South Bend (iusb.indiana.edu)",value: 'iusb'},
  {label: "Indiana University of Pennsylvania (iup.edu)",value: 'iup'},
  {label: "Indiana University Southeast at New Albany (ius.indiana.edu)",value: 'ius'},
  {label: "Indiana Wesleyan University, Marion (indwes.edu)",value: 'indwes'},
  {label: "Inter American University of Puerto Rico Metropolitan Campus (metro.inter.edu)",value: 'metro'},
  {label: "Iona College (iona.edu)",value: 'iona'},
  {label: "Iowa State University (iastate.edu)",value: 'iastate'},
  {label: "Ithaca College (ithaca.edu)",value: 'ithaca'},
  {label: "Jackson State University (jsums.edu)",value: 'jsums'},
  {label: "Jacksonville University (ju.edu)",value: 'ju'},
  {label: "Jacksonville State University (jsu.edu)",value: 'jsu'},
  {label: "James Madison University (jmu.edu)",value: 'jmu'},
  {label: "Jamestown College (jc.edu)",value: 'jc'},
  {label: "The Jewish Theological Seminary (jtsa.edu)",value: 'jtsa'},
  {label: "John Brown University (jbu.edu)",value: 'jbu'},
  {label: "John F. Kennedy University (jfku.edu)",value: 'jfku'},
  {label: "Johns Hopkins University (jhu.edu)",value: 'jhu'},
  {label: "Johnson Bible College (jbc.edu)",value: 'jbc'},
  {label: "Johnson C. Smith University (jcsu.edu)",value: 'jcsu'},
  {label: "Johnson & Wales University (jwu.edu)",value: 'jwu'},
  {label: "Johnson & Wales University-Charleston",value: 'johnson & wales '},
  {label: "Jones College (jones.edu)",value: 'jones'},
  {label: "Judson College (judson.edu)",value: 'judson'},
  {label: "Juniata College (juniata.edu)",value: 'juniata'},
  {label: "Kalamazoo College (kzoo.edu)",value: 'kzoo'},
  {label: "Kansas State University (ksu.edu)",value: 'ksu'},
  {label: "Kansas Wesleyan University (kwu.edu)",value: 'kwu'},
  {label: "Kean College (kean.edu)",value: 'kean'},
  {label: "Keene State College (keene.edu)",value: 'keene'},
  {label: "Kent State University (kent.edu)",value: 'kent'},
  {label: "Kenyon College (kenyon.edu)",value: 'kenyon'},
  {label: "King's College (kings.edu)",value: 'kings'},
  {label: "Knox College (knox.edu)",value: 'knox'},
  {label: "Kutztown University of Pennsylvania (kutztown.edu)",value: 'kutztown'},
  {label: "La Sierra University (lasierra.edu)",value: 'lasierra'},
  {label: "LaGrange College (lgc.peachnet.edu)",value: 'lgc'},
  {label: "Lafayette College (lafayette.edu)",value: 'lafayette'},
  {label: "Lake Forest College (lfc.edu)",value: 'lfc'},
  {label: "Lake Superior State University (lssu.edu)",value: 'lssu'},
  {label: "Lamar University (lamar.edu)",value: 'lamar'},
  {label: "Langston University (lunet.edu)",value: 'lunet'},
  {label: "LaSalle University (lasalle.edu)",value: 'lasalle'},
  {label: "Lawrence University (lawrence.edu)",value: 'lawrence'},
  {label: "Lawrence Technological University (ltu.edu)",value: 'ltu'},
  {label: "Lebanon Valley College (lvc.edu)",value: 'lvc'},
  {label: "Lehigh Univervsity (lehigh.edu)",value: 'lehigh'},
  {label: "Le Moyne College (lemoyne.edu)",value: 'lemoyne'},
  {label: "Lenoir-Rhyne College (lrc.edu)",value: 'lrc'},
  {label: "LeTourneau University (letu.edu)",value: 'letu'},
  {label: "Lewis & Clark College (lclark.edu)",value: 'lclark'},
  {label: "Lewis-Clark State College (lcsc.edu)",value: 'lcsc'},
  {label: "Lewis University (lewisu.edu)",value: 'lewisu'},
  {label: "Liberty University (liberty.edu)",value: 'liberty'},
  {label: "Lincoln University (lincoln.edu)",value: 'lincoln'},
  {label: "Linfield College (linfield.edu)",value: 'linfield'},
  {label: "Lock Haven University of Pennsylvania (lhup.edu)",value: 'lhup'},
  {label: "Loma Linda University (llu.edu)",value: 'llu'},
  {label: "Long Island University (liunet.edu)",value: 'liunet'},
  {label: "Longwood College (lwc.edu)",value: 'lwc'},
  {label: "Loras College (loras.edu)",value: 'loras'},
  {label: "Louisiana College (lacollege.edu)",value: 'lacollege'},
  {label: "Louisiana State University (lsu.edu)",value: 'lsu'},
  {label: "Louisiana State University at Alexandria (lsua.edu)",value: 'lsua'},
  {label: "Louisiana State University at Shreveport",value: 'louisiana state '},
  {label: "Louisiana Tech University (latech.edu)",value: 'latech'},
  {label: "Loyola College (loyola.edu)",value: 'loyola'},
  {label: "Loyola Marymount University (lmu.edu)",value: 'lmu'},
  {label: "Loyola University Chicago (luc.edu)",value: 'luc'},
  {label: "Luther College (luther.edu)",value: 'luther'},
  {label: "Luther Seminary (luthersem.edu)",value: 'luthersem'},
  {label: "Lycoming College (lycoming.edu)",value: 'lycoming'},
  {label: "Lynchburg College (lynchburg.edu)",value: 'lynchburg'},
  {label: "Lyndon State College (lsc.vsc.edu)",value: 'lsc'},
  {label: "Lyon College (lyon.edu)",value: 'lyon'},
  {label: "Macalester College (macalstr.edu)",value: 'macalstr'},
  {label: "Maharishi University of Management (mum.edu)",value: 'mum'},
  {label: "Maine Maritime Academy",value: 'maine maritime a'},
  {label: "Malone College (malone.edu)",value: 'malone'},
  {label: "Manhattan College (mancol.edu)",value: 'mancol'},
  {label: "Mankato State University (mankato.msus.edu)",value: 'mankato'},
  {label: "Mansfield University of Pennsylvania (mnsfld.edu)",value: 'mnsfld'},
  {label: "Marietta College (marietta.edu)",value: 'marietta'},
  {label: "Marist College (marist.edu)",value: 'marist'},
  {label: "Marlboro College (marlboro.edu)",value: 'marlboro'},
  {label: "Marquette University (mu.edu)",value: 'mu'},
  {label: "Marshall University (marshall.edu)",value: 'marshall'},
  {label: "Mary Baldwin College (mbc.edu)",value: 'mbc'},
  {label: "Marymount College (marymt.edu)",value: 'marymt'},
  {label: "Marymount University (marymount.edu)",value: 'marymount'},
  {label: "Mary Washington College (mwc.edu)",value: 'mwc'},
  {label: "Massachusetts Institute of Technology (mit.edu)",value: 'mit'},
  {label: "McMurry University (mcm.acu.edu)",value: 'mcm'},
  {label: "McNeese State University (mcneese.edu)",value: 'mcneese'},
  {label: "Medical College of Georgia (mcg.edu)",value: 'mcg'},
  {label: "Medical College of Wisconsin (mcw.edu)",value: 'mcw'},
  {label: "Mercer University (mercer.peachnet.edu)",value: 'mercer'},
  {label: "Mercyhurst College (mercy.edu)",value: 'mercy'},
  {label: "Meredith College (meredith.edu)",value: 'meredith'},
  {label: "Messiah College (messiah.edu)",value: 'messiah'},
  {label: "Metropolitan State College of Denver (mscd.edu)",value: 'mscd'},
  {label: "Metropolitan State University (metro.msus.edu)",value: 'metro'},
  {label: "Miami Christian University (mcu.edu))",value: 'mcu'},
  {label: "Miami University of Ohio (muohio.edu)",value: 'muohio'},
  {label: "Michigan State University (msu.edu)",value: 'msu'},
  {label: "Michigan Technological University (mtu.edu)",value: 'mtu'},
  {label: "Mid-America Nazarene College (manc.edu)",value: 'manc'},
  {label: "Middlebury College (middlebury.edu)",value: 'middlebury'},
  {label: "Middle Georgia College (mgc.peachnet.edu)",value: 'mgc'},
  {label: "Middle Tennessee State University (mtsu.edu)",value: 'mtsu'},
  {label: "Midwestern State University (mwsu.edu)",value: 'mwsu'},
  {label: "Millersville University of Pennsylvania (millersv.edu)",value: 'millersv'},
  {label: "Milligan College (milligan-college.tn.us)",value: 'milligan-college'},
  {label: "Millikin University (millikin.edu)",value: 'millikin'},
  {label: "Millsaps College (millsaps.edu)",value: 'millsaps'},
  {label: "Milwaukee School of Engineering (msoe.edu)",value: 'msoe'},
  {label: "Minot State University (misu.nodak.edu)",value: 'misu'},
  {label: "Minneapolis College of Art and Design (mcad.edu)",value: 'mcad'},
  {label: "Mississippi College (mc.edu)",value: 'mc'},
  {label: "Mississippi State University (msstate.edu)",value: 'msstate'},
  {label: "Mississippi University for Women (muw.edu)",value: 'muw'},
  {label: "Missouri Southern State College (mssc.edu)",value: 'mssc'},
  {label: "Missouri Western State College (mwsc.edu)",value: 'mwsc'},
  {label: "Molloy College (molloy.edu)",value: 'molloy'},
  {label: "Monmouth College (monm.edu)",value: 'monm'},
  {label: "Monmouth University (monmouth.edu)",value: 'monmouth'},
  {label: "Montana State University-Billings (msubillings.edu)",value: 'msubillings'},
  {label: "Montana State University-Bozeman (montana.edu)",value: 'montana'},
  {label: "Montana State University-Northern (nmclites.edu)",value: 'nmclites'},
  {label: "Montana Tech (mtech.edu)",value: 'mtech'},
  {label: "Montclair State University (montclair.edu)",value: 'montclair'},
  {label: "Montreat College (montreat.edu)",value: 'montreat'},
  {label: "Moravian College (moravian.edu)",value: 'moravian'},
  {label: "Moorhead State University (moorhead.msus.edu)",value: 'moorhead'},
  {label: "Morehouse College",value: 'morehouse colleg'},
  {label: "Morgan State University (morgan.edu)",value: 'morgan'},
  {label: "Mount Senario College (mscfs.edu)",value: 'mscfs'},
  {label: "Mount Holyoke College (mtholyoke.edu)",value: 'mtholyoke'},
  {label: "Mount Saint Joseph College (msjnet.edu)",value: 'msjnet'},
  {label: "Mount Saint Mary College (msmc.edu)",value: 'msmc'},
  {label: "Mount Union College (muc.edu)",value: 'muc'},
  {label: "Murray State University (mursuky.edu)",value: 'mursuky'},
  {label: "Muskingum College (muskingum.edu)",value: 'muskingum'},
  {label: "National Defense University (ndu.edu)",value: 'ndu'},
  {label: "National-Louis University (nl.edu)",value: 'nl'},
  {label: "National Technological University (ntu.edu)",value: 'ntu'},
  {label: "National University (nu.edu)",value: 'nu'},
  {label: "Naval Postgraduate School (nps.navy.mil)",value: 'nps'},
  {label: "Nazareth College (naz.edu)",value: 'naz'},
  {label: "Newberry College (newberry.edu)",value: 'newberry'},
  {label: "New England Institute of Technology",value: 'new england inst'},
  {label: "New College of California (newcollege.edu)",value: 'newcollege'},
  {label: "New Hampshire College (nhc.edu)",value: 'nhc'},
  {label: "New Jersey Institute of Technology (njit.edu)",value: 'njit'},
  {label: "New Mexico Highlands University (nmhu.edu)",value: 'nmhu'},
  {label: "New Mexico Institute of Mining & Technology (nmt.edu)",value: 'nmt'},
  {label: "New Mexico State University (nmsu.edu)",value: 'nmsu'},
  {label: "New York Institute of Technology (nyit.edu)",value: 'nyit'},
  {label: "New York University (nyu.edu)",value: 'nyu'},
  {label: "Niagara University (niagara.edu)",value: 'niagara'},
  {label: "Nicholls State University (nich.edu)",value: 'nich'},
  {label: "Norfolk State University (nsu.edu)",value: 'nsu'},
  {label: "North Adams State College (nasc.mass.edu)",value: 'nasc'},
  {label: "North Carolina Central University (NCCU.edu)",value: 'NCCU'},
  {label: "North Carolina A&T State University (ncat.edu)",value: 'ncat'},
  {label: "North Carolina State University (ncsu.edu)",value: 'ncsu'},
  {label: "North Carolina Wesleyan College (ncwc.edu)",value: 'ncwc'},
  {label: "North Central Bible College (ncbc.edu)",value: 'ncbc'},
  {label: "North Dakota State University (ndsu.nodak.edu)",value: 'ndsu'},
  {label: "Northland College (northland.edu)",value: 'northland'},
  {label: "North Park College and Theological Seminary (npcts.edu)",value: 'npcts'},
  {label: "Northeastern Illinois University",value: 'northeastern ill'},
  {label: "Northeastern Louisiana University (nlu.edu)",value: 'nlu'},
  {label: "Northeastern State University (nsuok.edu)",value: 'nsuok'},
  {label: "Northeastern University (northeastern.edu)",value: 'northeastern'},
  {label: "Northern Arizona University (nau.edu)",value: 'nau'},
  {label: "Northern Illinois University (niu.edu)",value: 'niu'},
  {label: "Northern Kentucky University (nku.edu)",value: 'nku'},
  {label: "Northern Michigan University (nmu.edu)",value: 'nmu'},
  {label: "Northern State University (northern.edu)",value: 'northern'},
  {label: "Northwest Missouri State University (nwmissouri.edu)",value: 'nwmissouri'},
  {label: "Northwest Nazarene College (nnc.edu)",value: 'nnc'},
  {label: "Northwestern College of Iowa (nwciowa.edu)",value: 'nwciowa'},
  {label: "Northwestern State University (nsula.edu)",value: 'nsula'},
  {label: "Northwestern University (nwu.edu)",value: 'nwu'},
  {label: "Norwich University (norwich.edu)",value: 'norwich'},
  {label: "Nova Southeastern University (nova.edu)",value: 'nova'},
  {label: "Oakland University (oakland.edu)",value: 'oakland'},
  {label: "Oberlin College (oberlin.edu)",value: 'oberlin'},
  {label: "Occidental College (oxy.edu)",value: 'oxy'},
  {label: "Ohio Dominican College (odc.edu)",value: 'odc'},
  {label: "Ohio Northern University (onu.edu)",value: 'onu'},
  {label: "Ohio State University, Columbus (ohio-state.edu)",value: 'ohio-state'},
  {label: "Ohio State University, Marion (marion.ohio-state.edu)",value: 'marion'},
  {label: "Ohio Wesleyan University (owu.edu)",value: 'owu'},
  {label: "Ohio University, Athens (ohiou.edu)",value: 'ohiou'},
  {label: "Oklahoma Baptist University (okbu.edu)",value: 'okbu'},
  {label: "Oklahoma City University (okcu.edu)",value: 'okcu'},
  {label: "Oklahoma State University (okstate.edu)",value: 'okstate'},
  {label: "Old Dominion University (odu.edu)",value: 'odu'},
  {label: "Olivet Nazarene University (olivet.edu)",value: 'olivet'},
  {label: "Oral Roberts University (oru.edu)",value: 'oru'},
  {label: "Oregon Graduate Institute of Science and Technology (ogi.edu)",value: 'ogi'},
  {label: "Oregon Health Sciences University (ohsu.edu)",value: 'ohsu'},
  {label: "Oregon Institute of Technology (oit.osshe.edu)",value: 'oit'},
  {label: "Oregon State University (orst.edu)",value: 'orst'},
  {label: "Otterbein College (otterbein.edu)",value: 'otterbein'},
  {label: "Our Lady of the Lake University (ollusa.edu)",value: 'ollusa'},
  {label: "Pace University (pace.edu)",value: 'pace'},
  {label: "Pacific Lutheran University (plu.edu)",value: 'plu'},
  {label: "Pacific Union College (puc.edu)",value: 'puc'},
  {label: "Pacific University (pacificu.edu)",value: 'pacificu'},
  {label: "Pacific Western University (pwu.com)",value: 'pwu'},
  {label: "Palm Beach Atlantic College (pbac.edu)",value: 'pbac'},
  {label: "Peace College (Peace.edu)",value: 'Peace'},
  {label: "Pembroke State University (pembroke.edu)",value: 'pembroke'},
  {label: "Pennsylvania State System of Higher Education (sshechan.edu)",value: 'sshechan'},
  {label: "Pennsylvania State University (psu.edu)",value: 'psu'},
  {label: "Pennsylvania State University-Schuylkill Campus (sl.psu.edu)",value: 'sl'},
  {label: "Pensacola Christian College (pcci.edu)",value: 'pcci'},
  {label: "Pepperdine University (pepperdine.edu)",value: 'pepperdine'},
  {label: "Peru State College (peru.edu)",value: 'peru'},
  {label: "Philadelphia College of Textiles and Science (philacol.edu)",value: 'philacol'},
  {label: "Phillips University (phillips.edu)",value: 'phillips'},
  {label: "Pittsburg State University (pittstate.edu)",value: 'pittstate'},
  {label: "Pitzer College (pitzer.edu)",value: 'pitzer'},
  {label: "Platt College (platt.edu)",value: 'platt'},
  {label: "Plymouth State College (plymouth.edu)",value: 'plymouth'},
  {label: "Point Loma Nazarene College",value: 'point loma nazar'},
  {label: "Polytechnic University of New York (poly.edu)",value: 'poly'},
  {label: "Polytechnic University of Puerto Rico (pupr.edu)",value: 'pupr'},
  {label: "Pomona College (pomona.edu)",value: 'pomona'},
  {label: "Portland State University (pdx.edu)",value: 'pdx'},
  {label: "Prairie View A&M University (pvamu.edu)",value: 'pvamu'},
  {label: "Pratt Institute (pratt.edu)",value: 'pratt'},
  {label: "Prescott College (asu.edu)",value: 'asu'},
  {label: "Princeton University (princeton.edu)",value: 'princeton'},
  {label: "Presbyterian College (presby.edu)",value: 'presby'},
  {label: "Providence College (providence.edu)",value: 'providence'},
  {label: "Purdue University (purdue.edu)",value: 'purdue'},
  {label: "Purdue University Calumet (purdue.edu)",value: 'purdue'},
  {label: "Purdue University North Central (purduenc.edu)",value: 'purduenc'},
  {label: "Quincy University (quincy.edu)",value: 'quincy'},
  {label: "Quinnipiac College (quinnipiac.edu)",value: 'quinnipiac'},
  {label: "Radford University (runet.edu)",value: 'runet'},
  {label: "Ramapo College (ramapo.edu)",value: 'ramapo'},
  {label: "Randolph-Macon College (rmc.edu)",value: 'rmc'},
  {label: "Randolph-Macon Woman's College (rmwc.edu)",value: 'rmwc'},
  {label: "Reed College (reed.edu)",value: 'reed'},
  {label: "Regent University (regent.edu)",value: 'regent'},
  {label: "Regis University (regis.edu)",value: 'regis'},
  {label: "Rensselaer Polytechnic Institute (rpi.edu)",value: 'rpi'},
  {label: "Rhode Island College (ric.edu)",value: 'ric'},
  {label: "Rhodes College (rhodes.edu)",value: 'rhodes'},
  {label: "Rice University (rice.edu)",value: 'rice'},
  {label: "Richard Stockton College of New Jersey (stockton.edu)",value: 'stockton'},
  {label: "Rider University (rider.edu)",value: 'rider'},
  {label: "Ripon College (Ripon.EDU)",value: 'Ripon'},
  {label: "Rivier College (riv.edu)",value: 'riv'},
  {label: "Roanoke College (roanoke.edu)",value: 'roanoke'},
  {label: "Rochester Institute of Technology (rit.edu)",value: 'rit'},
  {label: "The Rockefeller University (rockefeller.edu)",value: 'rockefeller'},
  {label: "Rockford College (rockford.edu)",value: 'rockford'},
  {label: "Rockhurst College (rockhurst.edu)",value: 'rockhurst'},
  {label: "Rocky Mountain College (rocky.edu)",value: 'rocky'},
  {label: "Roger Williams University (rwu.edu)",value: 'rwu'},
  {label: "Rollins College (rollins.edu)",value: 'rollins'},
  {label: "Rosary College (rosary.edu)",value: 'rosary'},
  {label: "Rose-Hulman Institute of Technology (rose-hulman.edu)",value: 'rose-hulman'},
  {label: "Rowan College (rowan.edu)",value: 'rowan'},
  {label: "Rutgers University (rutgers.edu)",value: 'rutgers'},
  {label: "Rutgers University, Camden (rutgers.edu)",value: 'rutgers'},
  {label: "Rutgers University, Newark (rutgers.edu)",value: 'rutgers'},
  {label: "The Sage Colleges (sage.edu)",value: 'sage'},
  {label: "Sacred Heart University (CT) (sacredheart.edu)",value: 'sacredheart'},
  {label: "Sacred Heart University (PR) (usc.clu.edu)",value: 'usc'},
  {label: "Saginaw Valley State University (svsu.edu)",value: 'svsu'},
  {label: "St. Ambrose University (sau.edu)",value: 'sau'},
  {label: "St. Andrews Presbyterian College (sapc.edu)",value: 'sapc'},
  {label: "Saint Anselm College (anselm.edu)",value: 'anselm'},
  {label: "St. Bonaventure University (sbu.edu)",value: 'sbu'},
  {label: "Saint Cloud State University (stcloud.msus.edu)",value: 'stcloud'},
  {label: "Saint Edward's University (stedwards.edu)",value: 'stedwards'},
  {label: "Saint Francis College (sfcpa.edu)",value: 'sfcpa'},
  {label: "St. John's College-Annapolis (sjca.edu)",value: 'sjca'},
  {label: "St. John's College-Santa Fe (sjcsf.edu)",value: 'sjcsf'},
  {label: "Saint John's University (MN) (csbsju.edu)",value: 'csbsju'},
  {label: "Saint John's University (NY) (stjohns.edu)",value: 'stjohns'},
  {label: "St. Joseph College (CT) (sjc.edu)",value: 'sjc'},
  {label: "Saint Joseph's College (IN) (saintjoe.edu)",value: 'saintjoe'},
  {label: "St. Joseph's College (ME) (sjcme.edu)",value: 'sjcme'},
  {label: "Saint Joseph's University (sju.edu)",value: 'sju'},
  {label: "St. Lawrence University (stlawu.edu)",value: 'stlawu'},
  {label: "St. Louis College of Pharmacy (stlcop.edu)",value: 'stlcop'},
  {label: "Saint Louis University (slu.edu)",value: 'slu'},
  {label: "St. Martin's College (stmartin.edu)",value: 'stmartin'},
  {label: "Saint Mary College (smcks.edu)",value: 'smcks'},
  {label: "Saint Mary's College (IN) (saintmarys.edu)",value: 'saintmarys'},
  {label: "Saint Mary's College of California (stmarys-ca.edu)",value: 'stmarys-ca'},
  {label: "Saint Mary's University of Minnesota (smumn.edu)",value: 'smumn'},
  {label: "Saint Michael's College (smcvt.edu)",value: 'smcvt'},
  {label: "Saint Olaf College (stolaf.edu)",value: 'stolaf'},
  {label: "St. Thomas University (FL) (stu.edu)",value: 'stu'},
  {label: "Saint Vincent College (stvincent.edu)",value: 'stvincent'},
  {label: "Saint Xavier University (sxu.edu)",value: 'sxu'},
  {label: "Salisbury State University (ssu.umd.edu)",value: 'ssu'},
  {label: "Salish Kootenai College (skc.edu)",value: 'skc'},
  {label: "Sam Houston State University (shsu.edu)",value: 'shsu'},
  {label: "Samford University (samford.edu)",value: 'samford'},
  {label: "San Diego State University (sdsu.edu)",value: 'sdsu'},
  {label: "San Francisco State University (sfsu.edu)",value: 'sfsu'},
  {label: "San Jose State University (sjsu.edu)",value: 'sjsu'},
  {label: "Santa Clara University (scu.edu)",value: 'scu'},
  {label: "Sarah Lawrence College (slc.edu)",value: 'slc'},
  {label: "School of the Art Institute of Chicago (artic.edu)",value: 'artic'},
  {label: "Seattle Pacific University (spu.edu)",value: 'spu'},
  {label: "Seattle University (seattleu.edu)",value: 'seattleu'},
  {label: "Seton Hall University (shu.edu)",value: 'shu'},
  {label: "Sewanee, University of the South (sewanee.edu)",value: 'sewanee'},
  {label: "Shawnee State University (shawnee.edu)",value: 'shawnee'},
  {label: "Shenandoah University (su.edu)",value: 'su'},
  {label: "Shippensburg University of Pennsylvania (ship.edu)",value: 'ship'},
  {label: "Shorter College (shorter.edu)",value: 'shorter'},
  {label: "Simmons College (simmons.edu)",value: 'simmons'},
  {label: "Simon's Rock College (simons-rock.edu)",value: 'simons-rock'},
  {label: "Simpson College (simpson.edu)",value: 'simpson'},
  {label: "Skidmore College (skidmore.edu)",value: 'skidmore'},
  {label: "Slippery Rock University of Pennsylvania (sru.edu)",value: 'sru'},
  {label: "Smith College (smith.edu)",value: 'smith'},
  {label: "Sonoma State University (sonoma.edu)",value: 'sonoma'},
  {label: "South Dakota School of Mines and Technology (sdsmt.edu)",value: 'sdsmt'},
  {label: "South Dakota State University (sdstate.edu)",value: 'sdstate'},
  {label: "Southeast Missouri State University (semo.edu)",value: 'semo'},
  {label: "Southeastern Louisiana University (selu.edu)",value: 'selu'},
  {label: "Southern College (southern.edu)",value: 'southern'},
  {label: "Southern College of Technology (sct.edu)",value: 'sct'},
  {label: "Southern Connecticut State University (scwww.ctstateu.edu)",value: 'scwww'},
  {label: "Southern Illinois University (siu.edu)",value: 'siu'},
  {label: "Southern Illinois University-Carbondale (siu.edu)",value: 'siu'},
  {label: "Southern Illinois University-Edwardsville (siue.edu)",value: 'siue'},
  {label: "Southern Methodist University (smu.edu)",value: 'smu'},
  {label: "Southern Nazarene University (snu.edu)",value: 'snu'},
  {label: "Southern Oregon State College (sosc.osshe.edu)",value: 'sosc'},
  {label: "Southern University (subr.edu)",value: 'subr'},
  {label: "Southern Utah University (suu.edu)",value: 'suu'},
  {label: "Southampton College (liunet.edu)",value: 'liunet'},
  {label: "South Texas College of Law (stcl.edu)",value: 'stcl'},
  {label: "Southwest Baptist University (sbuniv.edu)",value: 'sbuniv'},
  {label: "Southwest Missouri State University (smsu.edu)",value: 'smsu'},
  {label: "Southwest State University (southwest.msus.edu)",value: 'southwest'},
  {label: "Southwest Texas State University (swt.edu)",value: 'swt'},
  {label: "Southwestern Adventist College (swac.edu)",value: 'swac'},
  {label: "Southwestern University (southwestern.edu)",value: 'southwestern'},
  {label: "Spelman College (auc.edu)",value: 'auc'},
  {label: "Spring Arbor College (arbor.edu)",value: 'arbor'},
  {label: "Spring Hill College (shc.edu)",value: 'shc'},
  {label: "Stanford University (stanford.edu)",value: 'stanford'},
  {label: "State University of New York System (sunycentral.edu)",value: 'sunycentral'},
  {label: "State University of New York at Albany (albany.edu)",value: 'albany'},
  {label: "State University of New York College of Technology at Alfred (alfredtech.edu)",value: 'alfredtech'},
  {label: "State University of New York at Binghamton (binghamton.edu)",value: 'binghamton'},
  {label: "State University of New York College at Brockport (brockport.edu)",value: 'brockport'},
  {label: "State University of New York at Buffalo (buffalo.edu)",value: 'buffalo'},
  {label: "State University of New York College at Buffalo (Buffalo State College) (snybuf.edu)",value: 'snybuf'},
  {label: "State University of New York College of Agriculture and Technology at Cobleskill (cobleskill.edu)",value: 'cobleskill'},
  {label: "State University of New York College at Cortland (cortland.edu)",value: 'cortland'},
  {label: "State University of New York College of Environmental Science and Forestry (esf.edu)",value: 'esf'},
  {label: "State University of New York at Farmingdale (farmingdale.edu)",value: 'farmingdale'},
  {label: "State University of New York at Fredonia (fredonia.edu)",value: 'fredonia'},
  {label: "State University of New York College at Geneseo (geneseo.edu)",value: 'geneseo'},
  {label: "State University of New York College at New Paltz (newpaltz.edu)",value: 'newpaltz'},
  {label: "State University of New York College at Oneonta",value: 'state university'},
  {label: "State University of New York at Oswego (oswego.edu)",value: 'oswego'},
  {label: "State University of New York at Plattsburgh (plattsburgh.edu)",value: 'plattsburgh'},
  {label: "State University of New York College at Potsdam (potsdam.edu)",value: 'potsdam'},
  {label: "State University of New York at Stony Brook (sunysb.edu)",value: 'sunysb'},
  {label: "State University of New York Institute of Technology at Utica/Rome (sunyit.edu)",value: 'sunyit'},
  {label: "Stephen F. Austin State University (sfasu.edu)",value: 'sfasu'},
  {label: "Stephens College (stephens.edu)",value: 'stephens'},
  {label: "Stetson University (stetson.edu)",value: 'stetson'},
  {label: "Stevens Institute of Technology (stevens-tech.edu)",value: 'stevens-tech'},
  {label: "Strayer College (strayer.edu)",value: 'strayer'},
  {label: "Suffolk University (suffolk.edu)",value: 'suffolk'},
  {label: "Sul Ross State University (sulross.edu)",value: 'sulross'},
  {label: "Summit University of Louisiana (summitunivofla.edu)",value: 'summitunivofla'},
  {label: "Susquehanna University (susqu.edu)",value: 'susqu'},
  {label: "Swarthmore College (swarthmore.edu)",value: 'swarthmore'},
  {label: "Sweet Briar College (sbc.edu)",value: 'sbc'},
  {label: "Syracuse University (syr.edu)",value: 'syr'},
  {label: "Tabor College (tabor.edu)",value: 'tabor'},
  {label: "Tarleton State University (tarleton.edu)",value: 'tarleton'},
  {label: "Taylor University (tayloru.edu)",value: 'tayloru'},
  {label: "Teachers College, Columbia University (tc.columbia.edu)",value: 'tc'},
  {label: "Teikyo Marycrest University (mcrest.edu)",value: 'mcrest'},
  {label: "Temple University (temple.edu)",value: 'temple'},
  {label: "Tennessee State University (tnstate.edu)",value: 'tnstate'},
  {label: "Tennessee Technological University (tntech.edu)",value: 'tntech'},
  {label: "Texas A&M International University (tamiu.edu)",value: 'tamiu'},
  {label: "Texas A&M University-College Station (tamu.edu)",value: 'tamu'},
  {label: "Texas A&M University-Corpus Christi (tamucc.edu)",value: 'tamucc'},
  {label: "Texas A&M University-Kingsville (taiu.edu)",value: 'taiu'},
  {label: "Texas Christian University (tcu.edu)",value: 'tcu'},
  {label: "Texas Southern University (tsu.edu)",value: 'tsu'},
  {label: "Texas Tech University (ttu.edu)",value: 'ttu'},
  {label: "Texas Tech University-Health Sciences Center (ttuhsc.edu)",value: 'ttuhsc'},
  {label: "Texas Woman's University (twu.edu)",value: 'twu'},
  {label: "Thomas College (thomas.edu)",value: 'thomas'},
  {label: "Thomas Edison State College (tesc.edu)",value: 'tesc'},
  {label: "Thomas Jefferson University (tju.edu)",value: 'tju'},
  {label: "Thomas More College (thomasmore.edu)",value: 'thomasmore'},
  {label: "Towson State University (towson.edu)",value: 'towson'},
  {label: "Transylvania University (transy.edu)",value: 'transy'},
  {label: "Trenton State College (trenton.edu)",value: 'trenton'},
  {label: "Trinity College (CT) (trincoll.edu)",value: 'trincoll'},
  {label: "Trinity College (DC)",value: 'trinity college '},
  {label: "Trinity University (trinity.edu)",value: 'trinity'},
  {label: "Troy State University (tsufl.edu)",value: 'tsufl'},
  {label: "Truman State University (truman.edu)",value: 'truman'},
  {label: "Tucson University (tucsonu.edu)",value: 'tucsonu'},
  {label: "Tufts University (tufts.edu)",value: 'tufts'},
  {label: "Tulane University (tulane.edu)",value: 'tulane'},
  {label: "Tuskegee University (tusk.edu)",value: 'tusk'},
  {label: "Union College (union.edu)",value: 'union'},
  {label: "The Union Institute (tui.edu)",value: 'tui'},
  {label: "Union University (uu.edu)",value: 'uu'},
  {label: "United States Air Force Academy (usafa.af.mil)",value: 'usafa'},
  {label: "United States International University (usiu.edu)",value: 'usiu'},
  {label: "United States Merchant Marine Academy (usmma.edu)",value: 'usmma'},
  {label: "United States Military Academy (usma.edu)",value: 'usma'},
  {label: "United States Naval Academy (nadn.navy.mil)",value: 'nadn'},
  {label: "The Uniformed Services University of the Health Sciences (usuhs.mil)",value: 'usuhs'},
  {label: "Ursinus College (ursinus.edu)",value: 'ursinus'},
  {label: "Ursuline College",value: 'ursuline college'},
  {label: "University of Akron (uakron.edu)",value: 'uakron'},
  {label: "University of Alabama at Birmingham (uab.edu)",value: 'uab'},
  {label: "University of Alabama at Huntsville (uah.edu)",value: 'uah'},
  {label: "University of Alabama at Tuscaloosa (ua.edu)",value: 'ua'},
  {label: "University of Alaska (alaska.edu)",value: 'alaska'},
  {label: "University of Alaska-Anchorage (uaa.alaska.edu)",value: 'uaa'},
  {label: "University of Alaska-Fairbanks (alaska.edu)",value: 'alaska'},
  {label: "University of Alaska-Southeast (alaska.edu)",value: 'alaska'},
  {label: "University of Arizona (arizona.edu)",value: 'arizona'},
  {label: "University of Arkansas - Fayetteville (uark.edu)",value: 'uark'},
  {label: "University of Arkansas - Little Rock (ualr.edu)",value: 'ualr'},
  {label: "University of Arkansas for Medical Sciences (uams.edu)",value: 'uams'},
  {label: "University of Arkansas - Monticello (uamont.edu)",value: 'uamont'},
  {label: "University of Baltimore (ubalt.edu)",value: 'ubalt'},
  {label: "University of Bridgeport (bridgeport.edu)",value: 'bridgeport'},
  {label: "University of California, Berkeley (berkeley.edu)",value: 'berkeley'},
  {label: "University of California, Davis (ucdavis.edu)",value: 'ucdavis'},
  {label: "University of California, Irvine (uci.edu)",value: 'uci'},
  {label: "University of California, Los Angeles (ucla.edu)",value: 'ucla'},
  {label: "University of California, Riverside (ucr.edu)",value: 'ucr'},
  {label: "University of California, San Diego (ucsd.edu)",value: 'ucsd'},
  {label: "University of California, San Francisco (ucsf.edu)",value: 'ucsf'},
  {label: "University of California, Santa Barbara (ucsb.edu)",value: 'ucsb'},
  {label: "University of California, Santa Cruz (ucsc.edu)",value: 'ucsc'},
  {label: "University of Central Arkansas (uca.edu)",value: 'uca'},
  {label: "University of Central Florida (ucf.edu)",value: 'ucf'},
  {label: "University of Central Texas",value: 'university of ce'},
  {label: "University of Charleston (uchaswv.edu)",value: 'uchaswv'},
  {label: "University of Chicago (uchicago.edu)",value: 'uchicago'},
  {label: "University of Cincinnati (uc.edu)",value: 'uc'},
  {label: "University of Colorado at Boulder (colorado.edu)",value: 'colorado'},
  {label: "University of Colorado at Colorado Springs (uccs.edu)",value: 'uccs'},
  {label: "University of Colorado at Denver (cudenver.edu)",value: 'cudenver'},
  {label: "University of Colorado Health Sciences Center (hsc.colorado.edu)",value: 'hsc'},
  {label: "University of Connecticut (uconn.edu)",value: 'uconn'},
  {label: "University of Dallas (udallas.edu)",value: 'udallas'},
  {label: "University of Dayton (udayton.edu)",value: 'udayton'},
  {label: "University of Delaware (udel.edu)",value: 'udel'},
  {label: "University of Denver (du.edu)",value: 'du'},
  {label: "University of the District of Columbia (udc.edu)",value: 'udc'},
  {label: "University of Detroit Mercy (udmercy.edu)",value: 'udmercy'},
  {label: "University of Dubuque (dbq.edu)",value: 'dbq'},
  {label: "University of Evansville (evansville.edu)",value: 'evansville'},
  {label: "University of Florida (ufl.edu)",value: 'ufl'},
  {label: "University of Georgia (uga.edu)",value: 'uga'},
  {label: "University of Great Falls (ugf.edu)",value: 'ugf'},
  {label: "University of Guam (uog.edu)",value: 'uog'},
  {label: "University of Hartford (hartford.edu)",value: 'hartford'},
  {label: "University of Hawaii at Hilo Physics and Astronomy (uhh.hawaii.edu)",value: 'uhh'},
  {label: "University of Hawaii at Manoa (hawaii.edu)",value: 'hawaii'},
  {label: "University of Houston (uh.edu)",value: 'uh'},
  {label: "University of Idaho (uidaho.edu)",value: 'uidaho'},
  {label: "University of Illinois at Chicago (uic.edu)",value: 'uic'},
  {label: "University of Illinois at Springfield (sangamon.edu)",value: 'sangamon'},
  {label: "University of Ilinois at Urbana-Champaign (uiuc.edu)",value: 'uiuc'},
  {label: "University of Indianapolis (uindy.edu)",value: 'uindy'},
  {label: "University of Iowa (uiowa.edu)",value: 'uiowa'},
  {label: "University of Kansas (ukans.edu)",value: 'ukans'},
  {label: "University of Kansas School of Medicine (kumc.edu)",value: 'kumc'},
  {label: "University of Kentucky (uky.edu)",value: 'uky'},
  {label: "University of La Verne (ulaverne.edu)",value: 'ulaverne'},
  {label: "University of Louisville (louisville.edu)",value: 'louisville'},
  {label: "University of Maine System (maine.edu)",value: 'maine'},
  {label: "University of Maine (ume.maine.edu)",value: 'ume'},
  {label: "University of Maine at Farmington (umf.maine.edu)",value: 'umf'},
  {label: "University of Maine at Fort Kent (umfk.maine.edu)",value: 'umfk'},
  {label: "University of Maine at Machias (umm.maine.edu)",value: 'umm'},
  {label: "University of Maine at Presque Island (umpi.maine.edu)",value: 'umpi'},
  {label: "University of Maryland at Baltimore (ab.umd.edu)",value: 'ab'},
  {label: "University of Maryland at Baltimore County (umbc.edu)",value: 'umbc'},
  {label: "University of Maryland at College Park (umcp.umd.edu)",value: 'umcp'},
  {label: "University of Maryland - University College (umuc.edu)",value: 'umuc'},
  {label: "University of Massachusetts System (umassp.edu)",value: 'umassp'},
  {label: "University of Massachusetts at Amherst (umass.edu)",value: 'umass'},
  {label: "University of Massachusetts at Dartmouth (umassd.edu)",value: 'umassd'},
  {label: "University of Massachusetts at Lowell (uml.edu)",value: 'uml'},
  {label: "University of Memphis (memphis.edu)",value: 'memphis'},
  {label: "University of Miami (miami.edu)",value: 'miami'},
  {label: "University of Michigan-Ann Arbor (umich.edu)",value: 'umich'},
  {label: "University of Michigan-Dearborn (umd.umich.edu)",value: 'umd'},
  {label: "University of Minnesota (umn.edu)",value: 'umn'},
  {label: "University of Minnesota-Crookston (crk.umn.edu)",value: 'crk'},
  {label: "University of Minnesota-Duluth (d.umn.edu)",value: 'd'},
  {label: "University of Minnesota-Morris (mrs.umn.edu)",value: 'mrs'},
  {label: "University of Minnesota-Twin Cities (umn.edu)",value: 'umn'},
  {label: "University of Mississippi (olemiss.edu)",value: 'olemiss'},
  {label: "University of Mississippi Medical Center (umsmed.edu)",value: 'umsmed'},
  {label: "University of Missouri System (missouri.edu)",value: 'missouri'},
  {label: "University of Missouri-Columbia (missouri.edu)",value: 'missouri'},
  {label: "University of Missouri-Kansas City (umkc.edu)",value: 'umkc'},
  {label: "University of Missouri-Rolla (umr.edu)",value: 'umr'},
  {label: "University of Missouri-Saint Louis (umsl.edu)",value: 'umsl'},
  {label: "University of Montana (umt.edu)",value: 'umt'},
  {label: "University of Nebraska, Kearney (unk.edu)",value: 'unk'},
  {label: "University of Nebraska, Lincoln (unl.edu)",value: 'unl'},
  {label: "University of Nebraska, Omaha (unomaha.edu)",value: 'unomaha'},
  {label: "University of Nevada, Las Vegas (unlv.edu)",value: 'unlv'},
  {label: "University of Nevada, Reno (unr.edu)",value: 'unr'},
  {label: "University of New England (une.edu)",value: 'une'},
  {label: "University of New Hampshire, Durham (unh.edu)",value: 'unh'},
  {label: "University of New Haven (newhaven.edu)",value: 'newhaven'},
  {label: "University of New Mexico (unm.edu)",value: 'unm'},
  {label: "University of New Orleans (uno.edu)",value: 'uno'},
  {label: "University of North Carolina at Asheville (unca.edu)",value: 'unca'},
  {label: "University of North Carolina at Chapel Hill (unc.edu)",value: 'unc'},
  {label: "University of North Carolina at Charlotte (uncc.edu)",value: 'uncc'},
  {label: "University of North Carolina at Greensboro (uncg.edu)",value: 'uncg'},
  {label: "University of North Carolina System (unc.edu)",value: 'unc'},
  {label: "University of North Carolina at Wilmington (uncwil.edu)",value: 'uncwil'},
  {label: "University of North Dakota (und.nodak.edu)",value: 'und'},
  {label: "University of North Florida (unf.edu)",value: 'unf'},
  {label: "University of North Texas (unt.edu)",value: 'unt'},
  {label: "University of North Texas Health Science Center (hsc.unt.edu)",value: 'hsc'},
  {label: "University of Northern Colorado (univnorthco.edu)",value: 'univnorthco'},
  {label: "University of Northern Iowa (uni.edu)",value: 'uni'},
  {label: "University of Notre Dame (nd.edu)",value: 'nd'},
  {label: "University of Oklahoma (uoknor.edu)",value: 'uoknor'},
  {label: "University of Oregon (uoregon.edu)",value: 'uoregon'},
  {label: "University of the Ozarks (ozarks.edu)",value: 'ozarks'},
  {label: "University of the Pacific (uop.edu)",value: 'uop'},
  {label: "University of Pennsylvania (upenn.edu)",value: 'upenn'},
  {label: "University of Phoenix (uophx.edu)",value: 'uophx'},
  {label: "University of Pittsburgh (pitt.edu)",value: 'pitt'},
  {label: "University of Pittsburgh at Johnstown (pitt.edu)",value: 'pitt'},
  {label: "University of Portland (uofport.edu)",value: 'uofport'},
  {label: "University of Puerto Rico (upr.clu.edu)",value: 'upr'},
  {label: "University of Puget Sound (ups.edu)",value: 'ups'},
  {label: "University of Redlands (uor.edu)",value: 'uor'},
  {label: "University of Rhode Island (uri.edu)",value: 'uri'},
  {label: "University of Richmond (urich.edu)",value: 'urich'},
  {label: "University of Rochester (rochester.edu)",value: 'rochester'},
  {label: "University of San Diego (acusd.edu)",value: 'acusd'},
  {label: "University of San Francisco (usfca.edu)",value: 'usfca'},
  {label: "University of Sarasota (sarasota.fl.us)",value: 'sarasota'},
  {label: "University of Science & Arts of Oklahoma (usao.edu)",value: 'usao'},
  {label: "University of Scranton (uofs.edu)",value: 'uofs'},
  {label: "University of Sioux Falls (thecoo.edu)",value: 'thecoo'},
  {label: "University of Southern California (usc.edu)",value: 'usc'},
  {label: "University of South Carolina (scarolina.edu)",value: 'scarolina'},
  {label: "University of South Carolina - Aiken (sc.edu)",value: 'sc'},
  {label: "University of South Dakota (usd.edu)",value: 'usd'},
  {label: "University of South Florida (usf.edu)",value: 'usf'},
  {label: "University of Southern Maine (usm.maine.edu)",value: 'usm'},
  {label: "University of Southern Mississippi (usm.edu)",value: 'usm'},
  {label: "University of Southwestern Louisiana (usl.edu)",value: 'usl'},
  {label: "University of Saint Thomas (stthom.edu)",value: 'stthom'},
  {label: "University of Saint Thomas (MN) (stthomas.edu)",value: 'stthomas'},
  {label: "University of South Alabama (usouthal.edu)",value: 'usouthal'},
  {label: "University of Southern Colorado (uscolo.edu)",value: 'uscolo'},
  {label: "University of Southern Indiana (usi.edu)",value: 'usi'},
  {label: "University of Tampa (utampa.edu)",value: 'utampa'},
  {label: "University of Tennessee, Knoxville (utk.edu)",value: 'utk'},
  {label: "University of Tennessee, Martin (utm.edu)",value: 'utm'},
  {label: "University of Texas System (utsystem.edu)",value: 'utsystem'},
  {label: "University of Texas at Arlington (uta.edu)",value: 'uta'},
  {label: "University of Texas at Austin (utexas.edu)",value: 'utexas'},
  {label: "University of Texas at Brownsville (utb.edu)",value: 'utb'},
  {label: "University of Texas at Dallas (utdallas.edu)",value: 'utdallas'},
  {label: "University of Texas at El Paso (utep.edu)",value: 'utep'},
  {label: "University of Texas-Pan American (panam.edu)",value: 'panam'},
  {label: "University of Texas at San Antonio (utsa.edu)",value: 'utsa'},
  {label: "University of Texas Health Science Center at Houston (uth.tmc.edu)",value: 'uth'},
  {label: "University of Texas Health Science Center at San Antonio (uthscsa.edu)",value: 'uthscsa'},
  {label: "University of Texas at Tyler",value: 'university of te'},
  {label: "University of Texas Health Center at Tyler (uthct.edu)",value: 'uthct'},
  {label: "University of Texas M.D. Anderson Cancer Center (utmdacc.uth.tmc.edu)",value: 'utmdacc'},
  {label: "University of Texas Medical Branch (utmb.edu)",value: 'utmb'},
  {label: "University of Texas Southwestern Medical Center at Dallas (swmed.edu)",value: 'swmed'},
  {label: "University of Toledo (utoledo.edu)",value: 'utoledo'},
  {label: "University of Tulsa (utulsa.edu)",value: 'utulsa'},
  {label: "University of Utah (utah.edu)",value: 'utah'},
  {label: "University of Vermont (uvm.edu)",value: 'uvm'},
  {label: "University of the Virgin Islands (uvi.edu)",value: 'uvi'},
  {label: "University of Virginia, Charlottesville (virginia.edu)",value: 'virginia'},
  {label: "University of Washington (washington.edu)",value: 'washington'},
  {label: "University of West Alabama (westal.edu)",value: 'westal'},
  {label: "University of West Florida (uwf.edu)",value: 'uwf'},
  {label: "University of Wisconsin System (uwsa.edu)",value: 'uwsa'},
  {label: "University of Wisconsin-Eau Claire (uwec.edu)",value: 'uwec'},
  {label: "University of Wisconsin-Green Bay (uwgb.edu)",value: 'uwgb'},
  {label: "University of Wisconsin-LaCrosse (uwlax.edu)",value: 'uwlax'},
  {label: "University of Wisconsin-Madison (wisc.edu)",value: 'wisc'},
  {label: "University of Wisconsin-Milwaukee (uwm.edu)",value: 'uwm'},
  {label: "University of Wisconsin-Oshkosh (uwosh.edu)",value: 'uwosh'},
  {label: "University of Wisconsin-Parkside (uwp.edu)",value: 'uwp'},
  {label: "University of Wisconsin-Platteville (uwplatt.edu)",value: 'uwplatt'},
  {label: "University of Wisconsin-River Falls (uwrf.edu)",value: 'uwrf'},
  {label: "University of Wisconsin-Stevens Point (uwsp.edu)",value: 'uwsp'},
  {label: "University of Wisconsin-Stout (uwstout.edu)",value: 'uwstout'},
  {label: "University of Wisconsin-Superior (uwsuper.edu)",value: 'uwsuper'},
  {label: "University of Wisconsin-Whitewater (uww.edu)",value: 'uww'},
  {label: "University of Wyoming (uwyo.edu)",value: 'uwyo'},
  {label: "Upper Iowa University (uiu.edu)",value: 'uiu'},
  {label: "Utah State University (usu.edu)",value: 'usu'},
  {label: "Utah Valley State College (uvsc.edu)",value: 'uvsc'},
  {label: "Valley City State University (vcsu.nodak.edu)",value: 'vcsu'},
  {label: "Valdosta State University (valdosta.peachnet.edu)",value: 'valdosta'},
  {label: "Valparaiso University (valpo.edu)",value: 'valpo'},
  {label: "Vanderbilt University (vanderbilt.edu)",value: 'vanderbilt'},
  {label: "Vassar College (vassar.edu)",value: 'vassar'},
  {label: "Vermont Technical College (vtc.vsc.edu)",value: 'vtc'},
  {label: "Villa Julie College (vjc.edu)",value: 'vjc'},
  {label: "Villanova University (vill.edu)",value: 'vill'},
  {label: "Virginia Commonwealth University (vcu.edu)",value: 'vcu'},
  {label: "Virginia Intermont College (vic.edu)",value: 'vic'},
  {label: "Virginia Military Institute (vmi.edu)",value: 'vmi'},
  {label: "Virginia Polytechnic Institute and State University (vt.edu)",value: 'vt'},
  {label: "Virginia State University (vsu.edu)",value: 'vsu'},
  {label: "Virginia Wesleyan College (vwc.edu)",value: 'vwc'},
  {label: "Wabash College (wabash.edu)",value: 'wabash'},
  {label: "Wake Forest University (wfu.edu)",value: 'wfu'},
  {label: "Walden University (waldenu.edu)",value: 'waldenu'},
  {label: "Walla Walla College (wwc.edu)",value: 'wwc'},
  {label: "Warren Wilson College (warren-wilson.edu)",value: 'warren-wilson'},
  {label: "Wartburg College (wartburg.edu)",value: 'wartburg'},
  {label: "Washburn University (wuacc.edu)",value: 'wuacc'},
  {label: "Washington Bible College/Capital Bible Seminary (bible.edu)",value: 'bible'},
  {label: "Washington & Lee University (wlu.edu)",value: 'wlu'},
  {label: "Washington College (washcoll.edu)",value: 'washcoll'},
  {label: "Washington State University (wsu.edu)",value: 'wsu'},
  {label: "Washington State University at Tri-Cities (wsu.edu)",value: 'wsu'},
  {label: "Washington State University at Vancouver (vancouver.wsu.edu)",value: 'vancouver'},
  {label: "Washington University, Saint Louis (wustl.edu)",value: 'wustl'},
  {label: "Wayne State University (wayne.edu)",value: 'wayne'},
  {label: "Waynesburg College (waynesburg.edu)",value: 'waynesburg'},
  {label: "Weber State University (weber.edu)",value: 'weber'},
  {label: "Webster University (websteruniv.edu)",value: 'websteruniv'},
  {label: "Wellesley College (wellesley.edu)",value: 'wellesley'},
  {label: "Wells College (wells.edu)",value: 'wells'},
  {label: "Wentworth Institute of Technology (wit.edu)",value: 'wit'},
  {label: "Wesley College (wesley.edu)",value: 'wesley'},
  {label: "Wesleyan University (wesleyan.edu)",value: 'wesleyan'},
  {label: "West Chester University of Pennsylvania (wcupa.edu)",value: 'wcupa'},
  {label: "West Coast University (wcula.edu)",value: 'wcula'},
  {label: "West Georgia College (westga.edu)",value: 'westga'},
  {label: "West Liberty State College (wlsc.wvnet.edu)",value: 'wlsc'},
  {label: "West Texas A&M University (wtamu.edu)",value: 'wtamu'},
  {label: "West Virginia University (wvu.edu)",value: 'wvu'},
  {label: "West Virginia University at Parkersburg (wvup.wvnet.edu)",value: 'wvup'},
  {label: "Western Carolina University (wcu.edu)",value: 'wcu'},
  {label: "Western Connecticut State University (wcsu.ctstateu.edu)",value: 'wcsu'},
  {label: "Western Illinois University (wiu.edu)",value: 'wiu'},
  {label: "Western Kentucky University (wku.edu)",value: 'wku'},
  {label: "Western Maryland College (wmc.car.md.us)",value: 'wmc'},
  {label: "Western Michigan University (wmich.edu)",value: 'wmich'},
  {label: "Western Montana College (wmc.edu)",value: 'wmc'},
  {label: "Western New England College (wnec.edu)",value: 'wnec'},
  {label: "Western New Mexico University (wnmu.edu)",value: 'wnmu'},
  {label: "Western State College (wsc.colorado.edu)",value: 'wsc'},
  {label: "Western Washington University (wwu.edu)",value: 'wwu'},
  {label: "Westfield State College (wsc.mass.edu)",value: 'wsc'},
  {label: "Westminster College (westminster.edu)",value: 'westminster'},
  {label: "Westminster College (westminster-mo.edu)",value: 'westminster-mo'},
  {label: "Westminster College of Salt Lake City (wcslc.edu)",value: 'wcslc'},
  {label: "Westminster Theological Seminary (wts.edu)",value: 'wts'},
  {label: "Westmont College (westmont.edu)",value: 'westmont'},
  {label: "Wheaton College (wheaton.edu)",value: 'wheaton'},
  {label: "Wheaton College, Norton MA (wheatonma.edu)",value: 'wheatonma'},
  {label: "Wheeling Jesuit College (wjc.edu)",value: 'wjc'},
  {label: "Whitman College (whitman.edu)",value: 'whitman'},
  {label: "Whittier College (whittier.edu)",value: 'whittier'},
  {label: "Whitworth College (whitworth.edu)",value: 'whitworth'},
  {label: "Wichita State University (twsu.edu)",value: 'twsu'},
  {label: "Widener University (widener.edu)",value: 'widener'},
  {label: "Wilberforce University (wilberforce.edu)",value: 'wilberforce'},
  {label: "Wilkes University (wilkes.edu)",value: 'wilkes'},
  {label: "Willamette University (willamette.edu)",value: 'willamette'},
  {label: "William Howard Taft University (taftu.edu)",value: 'taftu'},
  {label: "William Jewell College (jewell.edu)",value: 'jewell'},
  {label: "William Mitchell College of Law (wmitchell.edu)",value: 'wmitchell'},
  {label: "William Penn College (wmpenn.edu)",value: 'wmpenn'},
  {label: "William Paterson College (wilpaterson.edu)",value: 'wilpaterson'},
  {label: "William Woods University (wmwoods.edu)",value: 'wmwoods'},
  {label: "Williams College (williams.edu)",value: 'williams'},
  {label: "Wilmington College (wilmington.edu)",value: 'wilmington'},
  {label: "Winona State University (winona.msus.edu)",value: 'winona'},
  {label: "Winthrop University (winthrop.edu)",value: 'winthrop'},
  {label: "Wittenberg University (wittenberg.edu)",value: 'wittenberg'},
  {label: "Wofford College (wofford.edu)",value: 'wofford'},
  {label: "Woodbury University (woodburyu.edu)",value: 'woodburyu'},
  {label: "Worcester Polytechnic Institute (wpi.edu)",value: 'wpi'},
  {label: "Wright State University (wright.edu)",value: 'wright'},
  {label: "Xavier University of Louisiana (xula.edu)",value: 'xula'},
  {label: "Yale University (yale.edu)",value: 'yale'},
  {label: "Yeshiva University (yu.edu)",value: 'yu'},
  {label: "York College of Pennsylvania (ycp.edu)",value: 'ycp'},
  {label: "Youngstown State University (ysu.edu)",value: 'ysu'}
];

export default universities;