name: Deploy Development with Docker

on:
  push:
    branches: [development]

concurrency:
  group: deploy-development
  cancel-in-progress: false

jobs:
  deploy:
    needs: [tests]
    environment: development
    runs-on: development-ui
    env:
      REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Certs
        run: |
          HOSTNAME=$(hostname)
          cp -rflT /etc/letsencrypt/live/$HOSTNAME/ certs/

      - name: Create .env file
        run: |
          cat <<EOF > .env
          REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }}
          EOF

      - name: Build container
        run: |
          docker compose build

      - name: Deploy container
        run: |
          docker compose up -d --remove-orphans --wait --wait-timeout 180

      - name: Remove docker artifacts
        run: |
          docker system prune -f

      - name: Notify deployment success
        run: echo "Deployment to development UI server successful!"

  tests:
    uses: ./.github/workflows/test_codepost_ui.yml
