name: Deploy Development with Docker

on:
  push:
    branches: [render]

jobs:
  deploy:
    environment: development
    runs-on: development-ui
    env:
      REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Certs
        run: |
          HOSTNAME=$(hostname)
          ln -s /etc/letsencrypt/live/$HOSTNAME certs
      - name: Create .env file
        run: |
          echo "REACT_APP_API_URL=$REACT_APP_API_URL" >> .env

      - name: Compose and build container
        run: |
          docker compose build
      - name: Compose and run container
        run: |
          docker compose up -d
