name: Deploy with Docker

on:
  push:
    branches: [render]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Certs
        run: |
          HOSTNAME=$(hostname)
          ln -s /etc/letsencrypt/live/$HOSTNAME certs

      - name: Build Docker image
        run: docker build -t codepost-ui:latest .

      - name: Stop and remove old container
        run: |
          docker stop codepost-ui || true
          docker rm codepost-ui || true

      - name: Run container
        run: |
          docker run -d --name codepost-ui codepost-ui:latest
